# -*- coding: utf-8 -*-
"""The model MCQs of UGC NET Paper I, from which ugc_paper1_mcqs.py writes
exams/ugc-net/paper-1/mcqs.html.

Each question is (stem, [A, B, C, D], key, explanation), in HTML. Units 3 and 7
have passages (in Unit 7, data sets): a ("PASSAGE", label, html) entry precedes
the five questions it serves, and its label names their numbers.

Written by Claude and checked by recheck_ugc_paper1.py; a unit is scored in the
web application only once the owner has approved it, and APPROVED records the
date of that approval (the page carries it as data-approved on the unit's
heading). A unit is added to UNITS in the batch that writes its notes.
"""

APPROVED = {}

U1 = [
 ("Who proposed the memory level of teaching?", ["J. F. Herbart", "H. C. Morrison", "H. Hunt", "B. S. Bloom"], "A",
  "The memory level, the lowest and most teacher-centred, is Herbart's; the understanding level is Morrison's and the reflective level Hunt's."),
 ("The reflective level of teaching is associated with:", ["Herbart", "Morrison", "Hunt", "Skinner"], "C",
  "Hunt's reflective level is the highest: learner-centred, built on problem-solving and critical thinking."),
 ("In the revised taxonomy of Anderson and Krathwohl (2001), the highest level of the cognitive domain is:", ["Evaluate", "Synthesis", "Analyse", "Create"], "D",
  "The revision renamed the levels as verbs and put <em>create</em> (once synthesis) above <em>evaluate</em>. Synthesis is the old name, not a level of the revision."),
 ("\"Valuing\" is a level of which domain of educational objectives?", ["Affective", "Cognitive", "Psychomotor", "Conative"], "A",
  "The affective domain (Krathwohl, Bloom and Masia, 1964) runs receiving, responding, valuing, organisation, characterisation."),
 ("The phase of teaching in which the teacher decides objectives, content and method is the:", ["Interactive phase", "Post-active phase", "Pre-active phase", "Evaluative phase"], "C",
  "Planning comes before the class: the pre-active phase. The interactive phase is the class itself; the post-active phase is evaluation afterwards."),
 ("A teacher starts with the scores of a real cricket match before defining the arithmetic mean. Which maxim is being followed?", ["Abstract to concrete", "Concrete to abstract", "General to particular", "Logical to psychological"], "B",
  "Real scores are concrete; the definition is abstract. The maxim is concrete to abstract (and particular to general, not general to particular)."),
 ("Andragogy, the art and science of helping adults learn, was popularised by:", ["Malcolm Knowles", "Jean Piaget", "Erik Erikson", "Edgar Dale"], "A",
  "Knowles set andragogy against pedagogy. Piaget described cognitive stages, Erikson psychosocial stages, Dale the cone of experience."),
 ("In Piaget's theory, abstract and hypothetical reasoning develops from about the age of eleven, in the:", ["Sensorimotor stage", "Pre-operational stage", "Concrete operational stage", "Formal operational stage"], "D",
  "Formal operations begin around eleven or twelve, which is why adolescents can handle abstract ideas that younger children cannot."),
 ("Which is NOT one of Knowles' assumptions about adult learners?", ["They are self-directed", "Their orientation is problem-centred", "Their motivation is mainly external", "Their experience is a resource for learning"], "C",
  "Knowles held that adults' motivation is mainly internal (self-esteem, satisfaction, quality of life). The other three are among his assumptions."),
 ("A class of 150 students taught together in one hall is a factor affecting teaching related mainly to:", ["The learner", "Support material", "The teacher's personality", "The institution"], "D",
  "Class size is set by the institution's policies and resources, so it is an institutional factor."),
 ("Which of these is a learner-centred method?", ["Lecture", "Demonstration", "Project method", "Recitation"], "C",
  "In the project method learners plan and carry out a purposeful task; the teacher guides. Lecture, demonstration and recitation are teacher-centred."),
 ("The project method of teaching was developed by:", ["W. H. Kilpatrick", "H. E. Armstrong", "Helen Parkhurst", "B. F. Skinner"], "A",
  "Kilpatrick set it out in 1918, drawing on Dewey. Armstrong is known for the heuristic method, Parkhurst for the Dalton plan, Skinner for programmed instruction."),
 ("Programmed instruction, in small steps with immediate feedback, is associated with:", ["Fred Keller", "B. F. Skinner", "Alex Osborn", "Ned Flanders"], "B",
  "Skinner's linear programming grew from his work on reinforcement. Keller devised the Personalised System of Instruction, Osborn brainstorming, Flanders interaction analysis."),
 ("In a flipped classroom:", ["Learners meet the content before class and use class time for problems and discussion", "The teacher lectures in class and sets exercises as homework", "All teaching is online and there are no classes", "There is no assessment"], "A",
  "The usual order is flipped: first contact with the content is at home (video, reading), and class time is for active work."),
 ("SWAYAM stands for:", ["System for Web-based Advanced Youth Academic Modules", "Study Without Age Yet Aiming at Mastery", "Study Webs of Active-Learning for Young Aspiring Minds", "Scheme for Web Access for Young Academic Minds"], "C",
  "SWAYAM, launched in 2017, is the Government of India's MOOC platform: Study Webs of Active-Learning for Young Aspiring Minds."),
 ("Which is NOT one of the four quadrants of a SWAYAM course?", ["E-tutorial", "E-content", "Discussion forum", "Classroom attendance"], "D",
  "The four quadrants are e-tutorial, e-content, self-assessment and a discussion forum. Attendance in a classroom is not part of a MOOC."),
 ("In Edgar Dale's Cone of Experience, the most abstract experiences, at the top of the cone, are:", ["Direct, purposeful experiences", "Verbal symbols", "Demonstrations", "Field trips"], "B",
  "Direct, purposeful experiences form the base; verbal symbols, which depend on words alone, sit at the top."),
 ("Evaluation carried out during teaching, to give feedback that improves learning while it is going on, is:", ["Summative", "Formative", "Placement", "Norm-referenced"], "B",
  "Formative evaluation happens during teaching and shapes it; summative evaluation judges at the end. Scriven introduced the two terms in 1967."),
 ("A test that compares each candidate's performance with a fixed standard of mastery, not with other candidates, is:", ["Norm-referenced", "Diagnostic", "Placement", "Criterion-referenced"], "D",
  "Criterion-referenced tests measure against a standard; norm-referenced tests rank candidates against one another (Glaser, 1963)."),
 ("Under CBCS a student earns grade points 8, 6 and 10 in courses of 4, 3 and 3 credits. The SGPA is:", ["8.0", "7.9", "8.2", "8.4"], "A",
  "SGPA = (4&times;8 + 3&times;6 + 3&times;10) / (4 + 3 + 3) = (32 + 18 + 30) / 10 = 8.0. Here the simple mean of the grade points is also 8.0, but only by chance: always weight by credits."),
]

U2 = [
 ("Action research, in which practitioners study and improve their own practice, was introduced by:", ["Kurt Lewin", "Karl Popper", "Auguste Comte", "Max Weber"], "A",
  "Lewin introduced action research in the 1940s; Stephen Corey took it into education. Popper is known for falsification, Comte for positivism, Weber for Verstehen."),
 ("Research carried out to solve an immediate practical problem is called:", ["Fundamental research", "Applied research", "Conceptual research", "Historical research"], "B",
  "Applied research aims at a practical solution; fundamental (pure) research aims to extend knowledge or theory."),
 ("Positivism as a philosophy of knowledge is associated with:", ["Karl Popper", "Max Weber", "Barney Glaser", "Auguste Comte"], "D",
  "Comte founded positivism. Popper's falsification underlies post-positivism; Weber's Verstehen, interpretivism; Glaser, grounded theory."),
 ("The principle that a scientific statement must be capable of being shown false is:", ["Verification", "Falsification", "Triangulation", "Replication"], "B",
  "Popper's falsification: one black swan refutes \"all swans are white\", but no number of white swans proves it."),
 ("Which method of research can directly establish a cause-and-effect relationship?", ["Survey", "Case study", "Experimental", "Historical"], "C",
  "Only the experimental method manipulates the presumed cause while controlling other variables. Surveys and case studies can show association, not cause."),
 ("A design with an experimental and a control group, but without random assignment to them, is:", ["True experimental", "Pre-experimental", "Ex post facto", "Quasi-experimental"], "D",
  "Random assignment is what makes a design truly experimental. A control group without it is quasi-experimental; one group without a control is pre-experimental."),
 ("In historical research, the process of checking whether a document is genuine is called:", ["Internal criticism", "External criticism", "Content analysis", "Triangulation"], "B",
  "External criticism tests authenticity (is it what it claims to be?); internal criticism tests the credibility of its content."),
 ("Grounded theory, which builds theory from the data rather than testing it, was developed by:", ["Campbell and Stanley", "Lazarsfeld and Katz", "Glaser and Strauss", "McCombs and Shaw"], "C",
  "Barney Glaser and Anselm Strauss, <em>The Discovery of Grounded Theory</em> (1967). Campbell and Stanley classified experimental designs."),
 ("A researcher studying a hidden population with no list of its members asks each participant to name others. This is:", ["Systematic sampling", "Stratified sampling", "Snowball sampling", "Cluster sampling"], "C",
  "Snowball sampling grows through referrals and suits hidden populations. The other three are probability methods that need a list or frame."),
 ("Which of the following is a probability sampling method?", ["Quota sampling", "Purposive sampling", "Convenience sampling", "Stratified random sampling"], "D",
  "In stratified random sampling every unit has a known chance of selection. Quota, purposive and convenience sampling are non-probability methods."),
 ("Arrange in the usual order: (i) review of literature (ii) data collection (iii) identifying the problem (iv) formulating hypotheses.", ["iii, i, iv, ii", "i, iii, iv, ii", "iii, iv, i, ii", "iv, iii, i, ii"], "A",
  "The problem comes first; the literature review shows what is known; hypotheses follow from both; data are collected to test them."),
 ("In a study of the effect of a teaching method on achievement, achievement is the:", ["Independent variable", "Dependent variable", "Extraneous variable", "Intervening variable"], "B",
  "The teaching method is the presumed cause (independent); achievement is the outcome measured (dependent)."),
 ("A hypothesis stating that there is no difference between two groups is the:", ["Alternative hypothesis", "Directional hypothesis", "Null hypothesis", "Research hypothesis"], "C",
  "The null hypothesis states no difference or no relation; it is the one tested statistically."),
 ("The referencing style that cites author and page in the text, as in (Rao 45), is:", ["MLA", "APA", "Vancouver", "IEEE"], "A",
  "MLA uses author&ndash;page. APA uses author&ndash;date (Rao, 2019); Vancouver and IEEE number their references."),
 ("In footnotes, \"ibid.\" means:", ["The same source as the previous note", "The work already cited, at another place", "Compare", "And others"], "A",
  "<em>Ibid.</em> (ibidem, in the same place) refers to the source cited immediately before. <em>Op. cit.</em> is the work already cited; <em>cf.</em> is compare; <em>et al.</em> is and others."),
 ("A researcher's six papers are cited 12, 10, 7, 5, 3 and 1 times. The researcher's h-index is:", ["3", "4", "5", "6"], "B",
  "Four papers have at least 4 citations (12, 10, 7, 5), but there are not five papers with at least 5 (the fifth has 3). So h = 4."),
 ("Shodhganga, maintained by INFLIBNET, is:", ["Plagiarism-detection software", "A MOOC platform", "A list of approved journals", "A repository of Indian PhD theses"], "D",
  "Shodhganga holds theses submitted to Indian universities. Plagiarism-detection software is provided through Shodh Shuddhi; SWAYAM is the MOOC platform."),
 ("Under the UGC plagiarism regulations of 2018, similarity of up to 10% is:", ["Level 0", "Level 1", "Level 2", "Level 3"], "A",
  "Level 0, up to 10%, is minor similarity and carries no penalty. Level 1 is above 10% to 40%, Level 2 above 40% to 60%, Level 3 above 60%."),
 ("In research misconduct, fabrication means:", ["Copying another's work without credit", "Changing data to fit the hypothesis", "Publishing the same work twice", "Making up data or results"], "D",
  "Fabrication is inventing data; falsification is changing them; plagiarism is copying without credit. Together they are the three serious forms of misconduct."),
 ("The three ethical principles of the Belmont Report (1979) are:", ["Consent, confidentiality and anonymity", "Validity, reliability and objectivity", "Respect for persons, beneficence and justice", "Honesty, openness and accountability"], "C",
  "The Belmont Report's principles are respect for persons, beneficence and justice; informed consent is how respect for persons is applied."),
]

P1 = """<p>For most of the twentieth century, India's farms drew their water from canals and tanks; today the larger share of irrigated land is watered from wells. The change brought great gains. A farmer with a tube well need not wait for a canal's turn; she can water when the crop needs it, and yields have risen accordingly. But groundwater is a bank account that is refilled only by the rain that soaks into the soil, and in many districts more is withdrawn each year than the monsoon returns. Water tables have fallen so far in places that wells must be deepened every few years, at a cost the poorest farmers cannot meet.</p>
<p>The difficulty is that no single farmer gains by holding back: water she leaves in the ground may simply be pumped by a neighbour. Free or cheap electricity for pumps, introduced to help farmers, has made the problem worse by removing the one cost that might have encouraged restraint. Some villages have shown another way. By agreeing among themselves which crops to grow and how much to pump, and by building small structures that slow run-off and let rain soak in, they have stabilised their water tables. Their experience suggests that the answer lies less in new technology than in new rules, made by those who share the resource.</p>"""

P2 = """<p>Before a scientific paper is published in a reputable journal, it is usually sent to two or three experts in the field who are not its authors. These reviewers judge whether the question is worth asking, whether the methods can answer it, and whether the conclusions follow from the results. They may recommend that the paper be accepted, revised or rejected. The system, called peer review, is often described as the gatekeeper of science.</p>
<p>Gatekeeper is too strong a word. Reviewers rarely see the raw data and almost never repeat the experiment; they judge the paper as it is written. They can miss honest errors, and a determined fraud may pass them altogether. Their judgement can also be coloured by the authors' reputation, which is why many journals now hide the authors' names from reviewers. None of this means that peer review is worthless: it catches many weak arguments and improves most of the papers that pass through it. But a reader should treat publication as a sign that a paper has been checked for sense, not as a guarantee that its findings are true. That guarantee, as far as science offers one, comes only when other researchers, working independently, find the same result.</p>"""

P3 = """<p>Children who begin school in a language they do not speak at home face two tasks at once: learning to read, and learning the language in which reading is taught. Many manage both, but many fall behind in the first years and never catch up. Studies in several countries have found that children taught first in their mother tongue learn to read sooner, and later learn a second language at least as well as children taught in it from the start. The skills of reading, it seems, transfer from one language to another; what does not transfer is the understanding of words never heard before.</p>
<p>Why, then, do many parents prefer that their children be taught from the first day in a language of wider use, such as English? Their reasons are not foolish. That language opens doors to higher education and to jobs, and parents fear that a child taught first at home will be left behind. The research suggests that their aim and the mother-tongue approach need not conflict: a strong start in the home language, with the second language introduced gradually and taught well, may be the surest route to the very fluency parents want. The difficulty is practical. It needs teachers and books in many languages, which poorer school systems find hard to provide.</p>"""

P4 = """<p>Every winter, thousands of volunteers in many countries spend a few hours counting the birds they see and send their tallies to a central database. No single count is precise: volunteers differ in skill, some days are cloudy, and a rare bird may be recorded twice or missed altogether. Yet taken together, over decades, such counts have revealed changes that no team of professionals could have measured alone, such as the slow northward shift of many species' winter ranges.</p>
<p>The value of such citizen science depends on its design. Volunteers must follow the same simple method, count for a fixed time in a fixed place, and record not only what they saw but how long they looked. With these details, statisticians can correct for differences in effort and skill. Without them, a rise in the number of birds recorded might mean only a rise in the number of people looking. The lesson reaches beyond birds: large amounts of imperfect data can answer questions that small amounts of perfect data cannot, provided the way the data were gathered is known.</p>"""

U3 = [
 ("PASSAGE", "Passage 1 (Questions 1&ndash;5)", P1),
 ("The passage is mainly about:", ["How tube wells have raised crop yields in India", "The gains of groundwater irrigation, its overuse, and how shared rules may help", "Why free electricity for farmers should be abolished", "Why canals are better than wells"], "B",
  "The first paragraph gives the gains and the overuse; the second, why it happens and what some villages did. (A) is one detail; (C) goes beyond the passage, which says cheap power worsened the problem but proposes no abolition; (D) is never argued."),
 ("According to the passage, why does no single farmer gain by pumping less?", ["The water she leaves may be pumped by a neighbour", "Her pump costs too much to run", "The monsoon refills her well every year", "Canals supply her instead"], "A",
  "The passage says so directly: \"water she leaves in the ground may simply be pumped by a neighbour\". (C) contradicts it: more is withdrawn than the monsoon returns."),
 ("In the passage, \"stabilised\" most nearly means:", ["Raised sharply", "Measured accurately", "Stopped from falling further", "Sold to neighbours"], "C",
  "The villages stopped the decline of their water tables. Nothing says the tables rose sharply, so (A) claims too much."),
 ("The author would most likely agree that:", ["New pumping technology will solve the problem", "Groundwater can never be replenished", "Poor farmers pump the most water", "Cooperation among those who share a resource can protect it"], "D",
  "The last sentence: the answer lies \"in new rules, made by those who share the resource\". (A) is what the author plays down; (B) contradicts \"refilled only by the rain\"."),
 ("The comparison of groundwater to \"a bank account\" is used to:", ["Explain that withdrawing more than is deposited runs the resource down", "Show that farmers have become wealthy", "Suggest that banks should pay for wells", "Describe how canals were run"], "A",
  "Rain is the deposit, pumping the withdrawal; when withdrawals exceed deposits, the balance (the water table) falls."),
 ("PASSAGE", "Passage 2 (Questions 6&ndash;10)", P2),
 ("The passage is mainly concerned with:", ["How to write a scientific paper", "The role and the limits of peer review", "Fraud in science", "Why journals hide authors' names"], "B",
  "It describes what peer review does and then what it cannot do. Fraud and hidden names are single points within that."),
 ("According to the passage, reviewers usually:", ["Repeat the experiment", "Examine the raw data", "Judge the paper as it is written", "Decide whether the authors are promoted"], "C",
  "\"Reviewers rarely see the raw data and almost never repeat the experiment; they judge the paper as it is written.\""),
 ("Why do many journals now hide the authors' names from reviewers?", ["Because reviewers' judgement can be coloured by the authors' reputation", "To save space in the journal", "To prevent fraud altogether", "Because authors ask them to"], "A",
  "The passage links the practice to reputation. It does not claim that hiding names prevents fraud; it says fraud may pass review."),
 ("It can be inferred that, in the author's view, the strongest evidence that a finding is true is:", ["Publication in a reputable journal", "Independent replication by other researchers", "Approval by three reviewers", "The reputation of the authors"], "B",
  "\"That guarantee &hellip; comes only when other researchers, working independently, find the same result.\" Publication is only \"a sign that a paper has been checked for sense\"."),
 ("The author regards the phrase \"gatekeeper of science\" as:", ["Exactly right", "An insult to reviewers", "Irrelevant", "An overstatement"], "D",
  "\"Gatekeeper is too strong a word.\" The author still values peer review, so (B) is wrong."),
 ("PASSAGE", "Passage 3 (Questions 11&ndash;15)", P3),
 ("Which best states the main idea of the passage?", ["Children should never be taught in English", "Parents who prefer English are foolish", "Starting school in the mother tongue can help both reading and later second-language learning, though it is hard to provide", "Reading skills cannot pass from one language to another"], "C",
  "The passage gives the evidence for a mother-tongue start, reconciles it with parents' aims, and names the practical difficulty. (B) contradicts \"their reasons are not foolish\"; (D) contradicts \"the skills of reading &hellip; transfer\"."),
 ("According to the passage, what does NOT transfer from one language to another?", ["The skills of reading", "Confidence in class", "The ability to write", "Understanding of words never heard before"], "D",
  "\"What does not transfer is the understanding of words never heard before.\" Reading skills, by contrast, do transfer."),
 ("The author's attitude to parents who prefer English from the first day is:", ["Understanding", "Contemptuous", "Indifferent", "Hostile"], "A",
  "The author explains their reasons (\"not foolish\": higher education, jobs) and argues their aim can be met another way."),
 ("The passage implies that a mother-tongue start:", ["Guarantees a good job", "May be the surest route to the fluency in a second language that parents want", "Should replace all teaching of a second language", "Costs nothing to provide"], "B",
  "The second paragraph says so. (C) contradicts \"the second language introduced gradually\"; (D) contradicts the last two sentences."),
 ("\"The difficulty is practical\" refers to:", ["The methods of teaching reading", "Parents' attitudes", "Providing teachers and books in many languages", "Children's ability to learn"], "C",
  "The next sentence explains it: the approach \"needs teachers and books in many languages\"."),
 ("PASSAGE", "Passage 4 (Questions 16&ndash;20)", P4),
 ("The best title for the passage is:", ["Many Imperfect Counts, Well Designed", "Why Volunteers Make Mistakes", "The Northward Shift of Birds", "Careers in Ornithology"], "A",
  "The passage is about how many imprecise counts, gathered by a known method, become valuable. (B) and (C) are single points."),
 ("Volunteers must record how long they looked so that:", ["They can be paid for their time", "Rare birds are not missed", "Each count becomes precise", "Statisticians can correct for differences in effort"], "D",
  "\"With these details, statisticians can correct for differences in effort and skill.\" Recording time does not make a single count precise."),
 ("\"A rise in the number of birds recorded might mean only a rise in the number of people looking.\" This sentence illustrates:", ["That birds are increasing", "Why the effort behind each count must be recorded", "That volunteers are dishonest", "That such counts are useless"], "B",
  "Without a record of effort, more observers would look like more birds. The passage does not say the counts are useless."),
 ("The author's tone towards citizen science is:", ["Dismissive", "Alarmed", "Balanced and appreciative", "Sarcastic"], "C",
  "The author admits each count's imprecision and praises what the counts reveal together."),
 ("Which statement is NOT supported by the passage?", ["A single count is imprecise", "Counts over decades revealed shifts in winter ranges", "Details of method let statisticians correct for effort", "Professionals could have measured these changes more easily on their own"], "D",
  "The passage says the opposite: the counts \"revealed changes that no team of professionals could have measured alone\"."),
]

U4 = [
 ("\"Who says what, in which channel, to whom, with what effect?\" is the model of communication given by:", ["Shannon and Weaver", "David Berlo", "Harold Lasswell", "Wilbur Schramm"], "C",
  "Lasswell's verbal model (1948) names the five questions."),
 ("The concept of \"noise\" in a model of communication was introduced by:", ["Aristotle", "Harold Lasswell", "Frank Dance", "Shannon and Weaver"], "D",
  "Shannon and Weaver's mathematical model (1948&ndash;49) added noise, anything that distorts the signal between transmitter and receiver."),
 ("In Berlo's SMCR model, the letters stand for:", ["Source, Message, Channel, Receiver", "Sender, Medium, Code, Response", "Signal, Message, Context, Reply", "Source, Meaning, Communication, Result"], "A",
  "Berlo (1960): Source, Message, Channel, Receiver, each with its own elements (skills, attitudes, knowledge, culture)."),
 ("Schramm's model of communication emphasises:", ["The overlap of the sender's and receiver's fields of experience", "A one-way flow from sender to receiver", "The capacity of the channel", "Communication growing like a helix"], "A",
  "Schramm (1954): communication works where the fields of experience overlap; his model is circular and interactive. The helix is Dance's."),
 ("A report sent by a subordinate to a superior is an example of:", ["Downward communication", "Horizontal communication", "Diagonal communication", "Upward communication"], "D",
  "Upward communication runs from subordinate to superior; downward, the other way; horizontal, between equals."),
 ("The grapevine in an organisation is an example of:", ["Formal communication", "Mass communication", "Informal communication", "Intrapersonal communication"], "C",
  "The grapevine runs outside official channels: informal communication."),
 ("The study of the use of space and distance in communication is called:", ["Kinesics", "Haptics", "Proxemics", "Chronemics"], "C",
  "Proxemics (Edward T. Hall). Kinesics is body movement, haptics touch, chronemics time."),
 ("Chronemics is the study of the use of:", ["Touch", "Eye contact", "Voice", "Time"], "D",
  "Chronemics covers punctuality, waiting and pauses: how time communicates."),
 ("Paralanguage refers to:", ["How words are said: pitch, tone, volume and pace", "Sign language", "Body posture", "Written symbols"], "A",
  "Paralanguage (vocalics) is the vocal part of speech other than the words themselves."),
 ("In Edward T. Hall's proxemics, the social distance zone is about:", ["Up to 45 cm", "45 cm to 1.2 m", "1.2 m to 3.6 m", "Beyond 3.6 m"], "C",
  "Intimate up to about 45 cm, personal about 45 cm to 1.2 m, social about 1.2 to 3.6 m, public beyond about 3.6 m."),
 ("Mehrabian's \"7&ndash;38&ndash;55\" finding applies to:", ["All communication", "Written communication", "Communication of feelings and attitudes when words and tone disagree", "Mass media"], "C",
  "The finding concerned messages about feelings and attitudes with inconsistent cues. Applying it to all communication is a common misquotation."),
 ("The distinction between high-context and low-context cultures was made by:", ["Geert Hofstede", "Bruce Tuckman", "Irving Janis", "Edward T. Hall"], "D",
  "Hall, in <em>Beyond Culture</em> (1976). Hofstede gave the dimensions of national culture; Tuckman the stages of groups; Janis groupthink."),
 ("Which is NOT one of Hofstede's dimensions of culture?", ["Power distance", "Uncertainty avoidance", "Individualism and collectivism", "High context and low context"], "D",
  "High and low context is Hall's distinction, not one of Hofstede's dimensions."),
 ("The correct order of Tuckman's stages of group development is:", ["Forming, norming, storming, performing", "Forming, storming, norming, performing", "Storming, forming, norming, performing", "Norming, forming, storming, performing"], "B",
  "Forming, storming, norming, performing (1965); adjourning was added in 1977."),
 ("In Flanders' Interaction Analysis Categories System, category 4 is:", ["Praises or encourages", "Asks questions", "Lectures", "Criticises or justifies authority"], "B",
  "Categories 1&ndash;4 are indirect teacher talk: 1 accepts feeling, 2 praises, 3 accepts or uses ideas, 4 asks questions. Lecturing is 5; criticising is 7."),
 ("How many categories does Flanders' Interaction Analysis Categories System have?", ["7", "10", "8", "12"], "B",
  "Ten: seven of teacher talk, two of student talk, and one for silence or confusion."),
 ("A lecturer uses technical terms with first-year students without explaining them. This is:", ["A physical barrier", "A semantic barrier", "A physiological barrier", "An organisational barrier"], "B",
  "Semantic barriers arise from language: jargon, ambiguity, unfamiliar words."),
 ("\"The medium is the message\" was said by:", ["Marshall McLuhan", "Wilbur Schramm", "Harold Lasswell", "Paul Lazarsfeld"], "A",
  "McLuhan, <em>Understanding Media</em> (1964), who also gave us the \"global village\"."),
 ("According to the agenda-setting theory of McCombs and Shaw, the mass media:", ["Tell people what to think", "Tell people what to think about", "Have no effect on public opinion", "Inject messages into a passive audience"], "B",
  "The media decide which issues people consider important, not their opinions on them. (D) describes the hypodermic needle theory."),
 ("India's first newspaper, Hicky's Bengal Gazette, began in:", ["1780", "1822", "1857", "1936"], "A",
  "James Augustus Hicky started it in Calcutta in 1780. 1936 is the year the name All India Radio was adopted."),
]

FOLLOW = ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"]

U5 = [
 ("What is the next term in the series 5, 11, 23, 47, 95, ?", ["189", "190", "191", "193"], "C",
  "Each term is twice the one before plus one: 5&times;2 + 1 = 11, 11&times;2 + 1 = 23, &hellip;, 95&times;2 + 1 = 191."),
 ("Proof by mathematical induction is:", ["An inductive generalisation from cases", "Abductive reasoning to the best explanation", "Reasoning by analogy", "A deductive proof"], "D",
  "Despite its name, mathematical induction proves a statement for every <em>n</em> from a base case and a step that is shown to hold in general, so the conclusion is certain: it is deduction."),
 ("Drawing a conclusion about all the voters of a state from a sample of 2,000 of them is:", ["Inductive reasoning", "Deductive reasoning", "Circular reasoning", "Reasoning by analogy"], "A",
  "It moves from particular cases (the sample) to a general claim (the population), and the conclusion is probable rather than certain: induction, in its statistical form."),
 ("What comes next in the letter series C, F, I, L, ?", ["M", "N", "O", "P"], "C",
  "The positions are 3, 6, 9, 12: add 3 each time, so 15, which is O."),
 ("What comes next in the letter series Z, X, V, T, ?", ["S", "Q", "P", "R"], "D",
  "The positions are 26, 24, 22, 20: subtract 2 each time, so 18, which is R."),
 ("If MANGO is coded as NBOHP, how is APPLE coded?", ["BQQMF", "BQPMF", "ZOOKD", "BPQMF"], "A",
  "Each letter moves one place forward: M&rarr;N, A&rarr;B, N&rarr;O, G&rarr;H, O&rarr;P. So A&rarr;B, P&rarr;Q, P&rarr;Q, L&rarr;M, E&rarr;F: BQQMF."),
 ("In a code, CAT is written XZG, each letter being replaced by its opposite in the alphabet (A&harr;Z, B&harr;Y, &hellip;). How is DOG written?", ["WLT", "WLS", "VLT", "WKT"], "A",
  "A letter's opposite has position 27 minus its own: D (4) &rarr; 23 = W, O (15) &rarr; 12 = L, G (7) &rarr; 20 = T. So WLT."),
 ("A man walks 6 km south, turns left and walks 8 km. How far is he from his starting point?", ["14 km", "10 km", "12 km", "2 km"], "B",
  "Facing south, a left turn faces east. The two legs are at right angles, so the distance is &radic;(6&sup2; + 8&sup2;) = &radic;100 = 10 km. 14 km is the distance walked, not the distance from the start."),
 ("A is the brother of B. B is the daughter of C. C is the husband of D. How is A related to D?", ["Brother", "Nephew", "Husband", "Son"], "D",
  "C is B's father and D, C's wife, is B's mother. A is B's brother, so A is also D's child, and a brother is male: A is D's son."),
 ("Which of these fractions is the largest?", ["3/4", "5/7", "7/9", "2/3"], "C",
  "As decimals: 3/4 = 0.75, 5/7 &asymp; 0.714, 7/9 &asymp; 0.778, 2/3 &asymp; 0.667. The largest is 7/9."),
 ("A car goes from P to Q at 30 km/h and returns at 60 km/h. Its average speed for the whole journey is:", ["45 km/h", "40 km/h", "42 km/h", "50 km/h"], "B",
  "For equal distances, average speed = 2 &times; 30 &times; 60 &divide; (30 + 60) = 3,600 &divide; 90 = 40 km/h. 45 km/h, the mean of the speeds, ignores that the slower leg takes twice as long."),
 ("A speed of 90 km/h, in metres per second, is:", ["30 m/s", "20 m/s", "32.4 m/s", "25 m/s"], "D",
  "Multiply by 5/18: 90 &times; 5 &divide; 18 = 25 m/s."),
 ("A train 200 m long, running at 72 km/h, passes a platform 300 m long. How long does it take?", ["15 seconds", "20 seconds", "25 seconds", "30 seconds"], "C",
  "72 km/h = 20 m/s. To pass the platform the train covers its own length and the platform's: (200 + 300) &divide; 20 = 25 seconds. 10 seconds would be for passing a pole."),
 ("The price of an article is raised by 10% and then lowered by 10%. The final price, as a percentage of the original, is:", ["100%", "99%", "98%", "101%"], "B",
  "100 &times; 1.10 &times; 0.90 = 99. The fall of 10% is taken on the higher price, so the net change is 10 &minus; 10 &minus; 10&times;10/100 = &minus;1%."),
 ("If A : B = 3 : 4 and B : C = 6 : 7, then A : B : C is:", ["9 : 12 : 14", "3 : 4 : 7", "18 : 24 : 21", "9 : 12 : 16"], "A",
  "Make B equal in both: 3 : 4 = 9 : 12 and 6 : 7 = 12 : 14. So A : B : C = 9 : 12 : 14."),
 ("An article bought for ₹1,250 is sold for ₹1,500. The profit percentage is:", ["15%", "25%", "16%", "20%"], "D",
  "Profit = 1,500 &minus; 1,250 = ₹250, and on cost it is 250 &divide; 1,250 &times; 100 = 20%. 16% (about 250 &divide; 1,500) takes the selling price as the base, which is wrong."),
 ("An article marked at ₹1,200 is sold after two successive discounts of 10% and 5%. The selling price is:", ["₹1,020", "₹1,080", "₹1,026", "₹1,140"], "C",
  "1,200 &times; 0.90 = 1,080, then 1,080 &times; 0.95 = ₹1,026. Two discounts of 10% and 5% are not one discount of 15% (which would give ₹1,020)."),
 ("The difference between compound and simple interest on ₹5,000 for 2 years at 8% a year is:", ["₹40", "₹32", "₹16", "₹64"], "B",
  "For two years, CI &minus; SI = P(R/100)&sup2; = 5,000 &times; 0.08 &times; 0.08 = ₹32. (SI = ₹800; CI = 5,000 &times; 1.08&sup2; &minus; 5,000 = ₹832.)"),
 ("The present value of ₹13,310 due in 3 years, at 10% a year compound interest, is:", ["₹10,000", "₹10,331", "₹9,900", "₹11,000"], "A",
  "Present value = 13,310 &divide; 1.1&sup3; = 13,310 &divide; 1.331 = ₹10,000. Discounting runs compound interest backwards."),
 ("In a class, 40 students average 50 marks and 60 students average 60 marks. The average of the whole class is:", ["55", "56", "54", "57"], "B",
  "Weighted average = (40 &times; 50 + 60 &times; 60) &divide; 100 = (2,000 + 3,600) &divide; 100 = 56. 55, the mean of the two averages, ignores that the groups differ in size."),
]

U6 = [
 ("Statements: All doctors are graduates. Some graduates are teachers.<br>Conclusions: I. Some doctors are teachers. II. Some teachers are graduates.", FOLLOW, "B",
  "I does not follow: the graduates who are teachers may all be outside the doctors. II follows: \"Some graduates are teachers\" converts to \"Some teachers are graduates\"."),
 ("Statements: No apple is a mango. All mangoes are fruits.<br>Conclusions: I. Some fruits are not apples. II. No fruit is an apple.", FOLLOW, "A",
  "Every mango is a fruit and no mango is an apple, so the mangoes are fruits that are not apples: I follows. II does not: there may be fruits outside the mangoes that are apples."),
 ("Statements: All pens are pencils. All pencils are erasers.<br>Conclusions: I. All pens are erasers. II. Some erasers are pens.", FOLLOW, "C",
  "I follows (Barbara: AAA in the first figure). II follows from I by conversion: if all pens are erasers and there are pens, some erasers are pens. Both follow."),
 ("Statements: Some cats are dogs. Some dogs are rats.<br>Conclusions: I. Some cats are rats. II. No cat is a rat.", FOLLOW, "D",
  "From two particular premises no conclusion follows. The dogs that are cats and the dogs that are rats may or may not overlap, so neither I nor II must be true."),
 ("Statements: No book is a pen. Some pens are boxes.<br>Conclusions: I. Some boxes are not books. II. Some books are boxes.", FOLLOW, "A",
  "The pens that are boxes cannot be books, so some boxes are not books: I follows. Nothing is said of books and boxes otherwise, so II does not follow."),
 ("\"If it is a mango, it is a fruit. It is a fruit. Therefore it is a mango.\" This argument:", ["Is modus ponens", "Is modus tollens", "Commits the fallacy of affirming the consequent", "Is a disjunctive syllogism"], "C",
  "It affirms the consequent (\"it is a fruit\") and concludes the antecedent. That form is invalid: a banana is a fruit too."),
 ("In an O proposition (\"Some S is not P\"), which term is distributed?", ["Both terms", "Neither term", "The subject only", "The predicate only"], "D",
  "O says that some S is excluded from the whole of P, so it distributes the predicate only. A distributes the subject, E both, I neither."),
 ("On the traditional square of opposition, if \"All S is P\" is false, then \"Some S is P\" is:", ["True", "False", "Undetermined", "Both true and false"], "C",
  "A false makes its contradictory O true, but tells us nothing about I, which can still be true or false. Only from A <em>true</em> does I follow."),
 ("\"No S is P\" and \"Some S is P\" are:", ["Contradictories", "Contraries", "Subcontraries", "Subalterns"], "A",
  "E and I differ in both quantity and quality, and exactly one of them is true: contradictories. The other pair of contradictories is A and O."),
 ("Two propositions that cannot both be false, though both may be true, are:", ["Contradictories", "Contraries", "Subalterns", "Subcontraries"], "D",
  "That is the relation of I and O, the subcontraries. Contraries (A and E) are the reverse: they cannot both be true but may both be false."),
 ("\"Everyone in my class is buying this phone, so it must be the best one.\" The fallacy is:", ["Ad hominem", "Ad populum", "Ad baculum", "Straw man"], "B",
  "It argues from popularity: appeal to the people (ad populum)."),
 ("\"No one has ever proved that ghosts do not exist, so they exist.\" The fallacy is:", ["Argument from ignorance (ad ignorantiam)", "Begging the question", "Appeal to authority", "Red herring"], "A",
  "It treats a lack of disproof as proof: the argument from ignorance."),
 ("By the law of inverse variation, as the connotation of a term increases, its denotation:", ["Increases", "Decreases, or stays the same", "Always stays the same", "Doubles"], "B",
  "Adding attributes narrows the class: animal &rarr; mammal &rarr; dog. Denotation falls, or at least does not rise."),
 ("A syllogism in which the middle term is the subject of the major premise and the predicate of the minor premise is in the:", ["Second figure", "Third figure", "First figure", "Fourth figure"], "C",
  "The first figure is M&ndash;P, S&ndash;M. The second is P&ndash;M, S&ndash;M; the third M&ndash;P, M&ndash;S; the fourth P&ndash;M, M&ndash;S."),
 ("Pen : Writer :: Scalpel : ?", ["Hospital", "Patient", "Knife", "Surgeon"], "D",
  "A pen is the tool of a writer; a scalpel is the tool of a surgeon. A knife is another tool, and the hospital and patient are the place and the person served."),
 ("How many pramanas does the Nyaya school accept?", ["Four", "Two", "Three", "Six"], "A",
  "Nyaya accepts perception, inference, comparison and verbal testimony. Bhatta Mimamsa and Advaita Vedanta accept six; Sankhya three; Buddhism and Vaisheshika two."),
 ("The only pramana the Charvaka school accepts is:", ["Anumana", "Pratyaksha", "Shabda", "Upamana"], "B",
  "Charvaka accepts perception (pratyaksha) alone, and rejects inference because no universal connection can be perceived."),
 ("In the inference \"The hill has fire, because it has smoke\", the paksha is:", ["Fire", "Smoke", "The hill", "The kitchen"], "C",
  "The paksha is the subject about which something is proved: the hill. Fire is the sadhya and smoke the hetu; the kitchen is the example (drishtanta)."),
 ("The hetvabhasa in which the reason proves the opposite of what is to be proved is:", ["Savyabhichara", "Asiddha", "Badhita", "Viruddha"], "D",
  "Viruddha, the contradictory reason, as in \"sound is eternal because it is produced\". Savyabhichara is the irregular reason, asiddha the unproved one, badhita the one contradicted by another pramana."),
 ("\"Devadatta is fat, yet he never eats by day; so he must eat at night.\" This knowledge comes from:", ["Anupalabdhi", "Arthapatti", "Upamana", "Pratyaksha"], "B",
  "It supposes the one fact that reconciles the two given facts: arthapatti, postulation."),
]

DS1 = """<p>The table shows the sales of three publishers, A, B and C, in thousands of copies.</p>
<table>
<tr><th>Publisher</th><th>2021</th><th>2022</th><th>2023</th><th>2024</th></tr>
<tr><td>A</td><td>30</td><td>36</td><td>45</td><td>54</td></tr>
<tr><td>B</td><td>40</td><td>38</td><td>42</td><td>48</td></tr>
<tr><td>C</td><td>25</td><td>30</td><td>33</td><td>36</td></tr>
</table>"""

DS2 = """<p>A college spent ₹50 lakh in one year, divided as follows.</p>
<table>
<tr><th>Head</th><th>Share of spending</th></tr>
<tr><td>Salaries</td><td>45%</td></tr>
<tr><td>Library</td><td>10%</td></tr>
<tr><td>Laboratories</td><td>15%</td></tr>
<tr><td>Maintenance</td><td>12%</td></tr>
<tr><td>Scholarships</td><td>8%</td></tr>
<tr><td>Others</td><td>10%</td></tr>
</table>"""

U7 = [
 ("PASSAGE", "Data set 1 (Questions 1&ndash;5)", DS1),
 ("What were the total sales of the three publishers in 2023?", ["115 thousand", "118 thousand", "120 thousand", "125 thousand"], "C",
  "45 + 42 + 33 = 120 thousand."),
 ("By what percentage did A's sales rise from 2023 to 2024?", ["18%", "20%", "25%", "22%"], "B",
  "(54 &minus; 45) &divide; 45 &times; 100 = 9 &divide; 45 &times; 100 = 20%. The base is the earlier year, 2023."),
 ("B's share of the total sales in 2022 was about:", ["36.5%", "38%", "35%", "40%"], "A",
  "The 2022 total is 36 + 38 + 30 = 104 thousand, and 38 &divide; 104 &times; 100 &asymp; 36.5%."),
 ("What were C's average annual sales over the four years?", ["30 thousand", "32 thousand", "31.5 thousand", "31 thousand"], "D",
  "(25 + 30 + 33 + 36) &divide; 4 = 124 &divide; 4 = 31 thousand."),
 ("In which year did B's sales fall compared with the year before?", ["2021", "2023", "2024", "2022"], "D",
  "B sold 40 in 2021 and 38 in 2022, a fall; it then rose to 42 and 48. 2021 has no earlier year in the table."),
 ("PASSAGE", "Data set 2 (Questions 6&ndash;10)", DS2),
 ("How much did the college spend on laboratories?", ["₹7.5 lakh", "₹6 lakh", "₹5 lakh", "₹8 lakh"], "A",
  "15% of ₹50 lakh = 0.15 &times; 50 = ₹7.5 lakh."),
 ("In a pie chart of this spending, the central angle of the Library sector is:", ["45°", "36°", "30°", "54°"], "B",
  "Each 1% takes 3.6&deg;, so 10% takes 36&deg;."),
 ("By how much did spending on salaries exceed spending on laboratories and scholarships together?", ["₹10 lakh", "₹12 lakh", "₹11 lakh", "₹11.5 lakh"], "C",
  "45% &minus; (15% + 8%) = 22% of ₹50 lakh = ₹11 lakh."),
 ("The ratio of spending on maintenance to spending on scholarships is:", ["3 : 2", "2 : 3", "4 : 3", "6 : 5"], "A",
  "12% : 8% = 12 : 8 = 3 : 2."),
 ("If the next year's budget is 20% larger and each head keeps its share, the library will receive:", ["₹5 lakh", "₹6 lakh", "₹6.5 lakh", "₹7 lakh"], "B",
  "The new budget is 50 &times; 1.2 = ₹60 lakh, and 10% of it is ₹6 lakh."),
 ("Data collected by an investigator for the purpose of the inquiry in hand are called:", ["Secondary data", "Tertiary data", "Administrative data", "Primary data"], "D",
  "Primary data are collected for the present purpose; secondary data were collected by someone else for another purpose."),
 ("A schedule, unlike a questionnaire, is filled in by:", ["The respondent", "The editor", "The enumerator", "The publisher"], "C",
  "The enumerator asks the questions and records the answers on a schedule; a questionnaire is filled in by the respondent."),
 ("Blood group is measured on which scale?", ["Nominal", "Ordinal", "Interval", "Ratio"], "A",
  "Blood groups are categories with no order: a nominal scale. Its proper average is the mode."),
 ("Which scale of measurement has a true zero, so that ratios are meaningful?", ["Nominal", "Ordinal", "Interval", "Ratio"], "D",
  "Only the ratio scale (height, income, marks) has a true zero; on an interval scale such as &deg;C, 40&deg; is not twice as hot as 20&deg;."),
 ("Temperature in degrees Celsius is measured on:", ["A nominal scale", "An ordinal scale", "An interval scale", "A ratio scale"], "C",
  "Differences are equal (10&deg; to 20&deg; is the same step as 30&deg; to 40&deg;) but 0 &deg;C is not an absence of heat: an interval scale."),
 ("The distribution of a continuous variable, such as the heights of students, is best shown by a:", ["Pie chart", "Histogram", "Bar chart of categories", "Line chart"], "B",
  "A histogram shows a continuous variable in adjoining class intervals. A bar chart compares separate categories; a pie chart shows shares of a whole; a line chart shows change over time."),
 ("In a histogram, the frequency of a class is represented by the bar's:", ["Height alone, whatever the width", "Width", "Area", "Colour"], "C",
  "Area represents frequency. With equal class widths the heights are in proportion too, but with unequal widths the heights must be adjusted."),
 ("The number of children in a family is:", ["A continuous variable", "A discrete variable", "A qualitative attribute", "An ordinal rank"], "B",
  "It can take only whole-number values, 0, 1, 2, &hellip;: discrete. Height or time would be continuous."),
 ("The National Data Sharing and Accessibility Policy (NDSAP), under which government data are published on data.gov.in, was notified in:", ["2005", "2016", "2023", "2012"], "D",
  "NDSAP was notified in 2012. 2023 is the year of the Digital Personal Data Protection Act; 2016 of the Aadhaar Act."),
 ("A choropleth map:", ["Shades each area by the value of a variable", "Places one dot for each fixed number of cases", "Sizes a symbol by the value", "Shows travel routes"], "A",
  "A choropleth map shades areas (districts, states) by their values, such as literacy rate. The others are dot maps, proportional-symbol maps and route maps."),
]

U8 = [
 ("One byte is made up of how many bits?", ["4", "8", "16", "1024"], "B",
  "A byte is 8 bits. 1,024 is the number of bytes in a kilobyte in computing usage."),
 ("Taking 1 KB as 1,024 bytes, how many bits are there in 2 KB?", ["16,000", "2,048", "8,192", "16,384"], "D",
  "2 KB = 2 &times; 1,024 = 2,048 bytes, and each byte is 8 bits: 2,048 &times; 8 = 16,384 bits. 2,048 is the number of bytes, not bits."),
 ("The binary number 1011 equals which decimal number?", ["9", "10", "11", "13"], "C",
  "1&times;8 + 0&times;4 + 1&times;2 + 1&times;1 = 8 + 0 + 2 + 1 = 11."),
 ("The binary number 11001 equals which decimal number?", ["25", "24", "19", "21"], "A",
  "1&times;16 + 1&times;8 + 0&times;4 + 0&times;2 + 1&times;1 = 16 + 8 + 1 = 25."),
 ("The Domain Name System (DNS):", ["Translates domain names into IP addresses", "Encrypts web pages", "Sends e-mail between servers", "Stores files in the cloud"], "A",
  "DNS turns a name such as ugc.gov.in into the IP address of the server. Encryption is HTTPS's job; sending mail is SMTP's."),
 ("Which protocol is used to send e-mail?", ["POP3", "IMAP", "SMTP", "FTP"], "C",
  "SMTP (Simple Mail Transfer Protocol) sends mail; POP3 and IMAP are used to receive it; FTP transfers files."),
 ("Which protocol keeps e-mail on the server and in step across a phone and a laptop?", ["POP3", "IMAP", "SMTP", "HTTP"], "B",
  "IMAP keeps messages on the server and synchronises every device. POP3 usually downloads mail to one device and removes it from the server."),
 ("The BCC field of an e-mail holds:", ["A copy for the sender only", "The main recipients", "The attachments", "Recipients whose addresses the other recipients cannot see"], "D",
  "BCC (blind carbon copy) recipients get the message, but no one else sees their addresses. CC recipients are visible to all."),
 ("HTTPS differs from HTTP in that it:", ["Is always faster", "Encrypts the connection between the browser and the server", "Works only on intranets", "Is used to send e-mail"], "B",
  "The S stands for secure: the traffic is encrypted (with TLS), so it cannot be read or altered on the way."),
 ("The World Wide Web was proposed in 1989 by:", ["Vint Cerf", "Ray Tomlinson", "Bill Gates", "Tim Berners-Lee"], "D",
  "Tim Berners-Lee proposed the web at CERN. Vint Cerf co-designed TCP/IP; Ray Tomlinson sent the first networked e-mail (1971)."),
 ("A private network that serves only the members of one organisation, using internet protocols, is:", ["The internet", "An extranet", "An intranet", "A wide area network"], "C",
  "An intranet is private to one organisation. An extranet extends it to chosen outsiders; the internet is public."),
 ("A university gives its affiliated colleges logins to upload marks to its private network. This is:", ["An extranet", "An intranet", "A LAN", "The internet"], "A",
  "A private network opened to selected outside users is an extranet."),
 ("A network that covers a city is a:", ["LAN", "MAN", "WAN", "PAN"], "B",
  "Metropolitan Area Network. A LAN covers a building or campus, a WAN a country or the world, a PAN a single person's devices."),
 ("An e-mail that pretends to come from a bank and asks you to enter your password on a linked page is:", ["Spam", "A firewall", "Encryption", "Phishing"], "D",
  "Phishing tricks people into giving up passwords or other details. Spam is unwanted bulk mail, which may or may not be phishing."),
 ("A webinar is:", ["A virus that spreads by e-mail", "A web browser", "A seminar held over the web, usually a few speakers to a large audience", "A type of cable"], "C",
  "A web seminar: speakers present live, and the audience usually listens and asks questions by chat."),
 ("The National Digital Library of India (NDLI) is developed by:", ["IIT Bombay", "INFLIBNET", "IIT Kharagpur", "IGNOU"], "C",
  "NDLI is developed by IIT Kharagpur under the Ministry of Education. INFLIBNET runs Shodhganga, e-ShodhSindhu and e-PG Pathshala."),
 ("e-PG Pathshala provides:", ["E-content for postgraduate subjects", "Television channels for schools", "Plagiarism-detection software", "Digital degree certificates"], "A",
  "It is the UGC's e-content programme for postgraduate subjects, run through INFLIBNET. Degree certificates are in DigiLocker through NAD."),
 ("The National Academic Depository (NAD), with DigiLocker, is used to:", ["Run online classes", "Keep and verify academic awards such as degrees in digital form", "Rank universities", "Fund research"], "B",
  "NAD holds degrees and mark sheets digitally, through DigiLocker, so they can be retrieved and verified. Ranking is NIRF's job."),
 ("The Digital India programme was launched in:", ["2006", "2014", "2020", "2015"], "D",
  "Digital India was launched on 1 July 2015. 2006 is the year of the National e-Governance Plan."),
 ("Online tendering for government contracts is an example of:", ["G2B", "G2C", "G2G", "G2E"], "A",
  "Government to business. Certificates and pensions for citizens are G2C; data shared between departments is G2G; payroll for staff is G2E."),
]

U9 = [
 ("How many Sustainable Development Goals are there?", ["8", "15", "17", "169"], "C",
  "17 goals (2015&ndash;2030), with 169 targets among them. 8 is the number of the earlier Millennium Development Goals."),
 ("The 17 Sustainable Development Goals contain how many targets?", ["17", "100", "230", "169"], "D",
  "169 targets, set out in the 2030 Agenda adopted in September 2015."),
 ("The Millennium Development Goals covered the period:", ["1990&ndash;2000", "2000&ndash;2015", "2015&ndash;2030", "1992&ndash;2012"], "B",
  "The eight MDGs came from the Millennium Declaration of 2000, with 2015 as the target year; the SDGs took over for 2015&ndash;2030."),
 ("SDG 4 is:", ["Zero hunger", "Quality education", "Gender equality", "Climate action"], "B",
  "SDG 4 is quality education. Zero hunger is SDG 2, gender equality SDG 5, climate action SDG 13."),
 ("A high biochemical oxygen demand (BOD) in a river indicates:", ["Heavy organic pollution", "Clean, well-oxygenated water", "High salinity", "A high fish population"], "A",
  "BOD measures the oxygen micro-organisms need to break down organic matter; sewage and other organic waste raise it and leave less oxygen for fish."),
 ("Minamata disease is caused by poisoning with:", ["Lead", "Cadmium", "Mercury", "Arsenic"], "C",
  "Mercury, from industrial discharge into Minamata Bay in Japan in the 1950s. Cadmium causes itai-itai disease."),
 ("Itai-itai disease is caused by:", ["Mercury", "Cadmium", "Lead", "Fluoride"], "B",
  "Cadmium poisoning, first recorded in Japan, softens the bones and damages the kidneys."),
 ("\"Blue baby syndrome\" (methaemoglobinaemia) in infants is linked to drinking water with excess:", ["Nitrate", "Fluoride", "Arsenic", "Lead"], "A",
  "Nitrate, often from fertiliser run-off, reduces the blood's ability to carry oxygen in infants. Excess fluoride causes fluorosis."),
 ("Noise is measured in:", ["Decibels", "Hertz", "Pascals", "Lux"], "A",
  "Decibels (dB), a logarithmic scale of sound intensity. Hertz measures frequency (pitch); lux measures light."),
 ("India's E-Waste (Management) Rules now in force were notified in:", ["2011", "2016", "2022", "2008"], "C",
  "The E-Waste (Management) Rules, 2022, based on extended producer responsibility. The solid, plastic, biomedical and hazardous waste rules date from 2016."),
 ("The gas that leaked in the Bhopal disaster of 1984 was:", ["Methyl isocyanate", "Chlorine", "Sulphur dioxide", "Ammonia"], "A",
  "Methyl isocyanate leaked from a pesticide plant in Bhopal in December 1984."),
 ("The Environment (Protection) Act was enacted in:", ["1972", "1974", "1981", "1986"], "D",
  "1986, after the Bhopal disaster. 1972 is the Wild Life (Protection) Act, 1974 the Water Act, 1981 the Air Act."),
 ("How many national missions does India's National Action Plan on Climate Change (2008) have?", ["6", "7", "8", "10"], "C",
  "Eight: solar, enhanced energy efficiency, sustainable habitat, water, the Himalayan ecosystem, green India, sustainable agriculture, and strategic knowledge for climate change."),
 ("Which of these is NOT one of the missions of the NAPCC?", ["National Solar Mission", "National Water Mission", "National Mission for a Green India", "National Nuclear Energy Mission"], "D",
  "There is no nuclear energy mission among the eight. Solar, water and green India are three of them."),
 ("The Montreal Protocol (1987) deals with:", ["Substances that deplete the ozone layer", "Greenhouse gas emission targets", "Biological diversity", "Trade in endangered species"], "A",
  "It phases out ozone-depleting substances such as CFCs. Greenhouse-gas targets are the business of the Kyoto Protocol and the Paris Agreement."),
 ("The Kyoto Protocol was adopted in:", ["1992", "1997", "2005", "2015"], "B",
  "Adopted in 1997, it came into force in 2005. 1992 is the Rio Summit; 2015 the Paris Agreement."),
 ("The Paris Agreement (2015) aims to hold the rise in global average temperature:", ["Below 4&deg;C", "At exactly 1&deg;C", "Below 3&deg;C, with no lower aim", "Well below 2&deg;C, pursuing efforts to limit it to 1.5&deg;C"], "D",
  "Well below 2&deg;C above pre-industrial levels, and pursuing 1.5&deg;C; each country sets its own Nationally Determined Contribution."),
 ("The International Solar Alliance, launched by India and France in 2015, has its headquarters in:", ["Paris", "Geneva", "Gurugram", "Bonn"], "C",
  "Gurugram, in Haryana, India. It was launched at the Paris climate conference in 2015."),
 ("The National Disaster Management Authority, set up under the Disaster Management Act, 2005, is chaired by:", ["The Home Minister", "The Prime Minister", "The President", "The Cabinet Secretary"], "B",
  "The Prime Minister chairs the NDMA; the Chief Ministers chair the state authorities."),
 ("The Sendai Framework for Disaster Risk Reduction covers the period:", ["2005&ndash;2015", "2000&ndash;2015", "2020&ndash;2035", "2015&ndash;2030"], "D",
  "2015&ndash;2030. It followed the Hyogo Framework for Action, 2005&ndash;2015."),
]

U10 = [
 ("Nalanda was founded in the 5th century CE under the king:", ["Dharmapala", "Kumaragupta I", "Ashoka", "Harsha"], "B",
  "Kumaragupta I of the Gupta dynasty. Harsha later patronised it; Dharmapala founded Vikramashila."),
 ("Vikramashila was founded by:", ["Dharmapala", "Gopala", "Kumaragupta I", "Kanishka"], "A",
  "The Pala king Dharmapala, in the late 8th century. Gopala founded Odantapuri."),
 ("The ancient centre of learning at Takshashila lies in present-day:", ["Bihar", "Gujarat", "Pakistan", "Afghanistan"], "C",
  "Takshashila (Taxila) is near Rawalpindi, Pakistan. Nalanda, Vikramashila and Odantapuri are in Bihar; Valabhi in Gujarat."),
 ("The University Education Commission of 1948&ndash;49 was chaired by:", ["D. S. Kothari", "A. L. Mudaliar", "S. Radhakrishnan", "K. Kasturirangan"], "C",
  "S. Radhakrishnan. Kothari chaired the Education Commission of 1964&ndash;66, Mudaliar the Secondary Education Commission, and Kasturirangan the committee that drafted NEP 2020."),
 ("The Education Commission chaired by D. S. Kothari sat in:", ["1948&ndash;49", "1952&ndash;53", "1986&ndash;92", "1964&ndash;66"], "D",
  "1964&ndash;66; its report, Education and National Development, led to the first National Policy on Education (1968)."),
 ("The University Grants Commission became a statutory body by an Act of:", ["1953", "1956", "1964", "1986"], "B",
  "The UGC Act, 1956. The Commission had been inaugurated in 1953."),
 ("NEP 2020 aims to raise the gross enrolment ratio in higher education to:", ["50% by 2035", "100% by 2030", "35% by 2025", "60% by 2040"], "A",
  "NEP 2020 sets a gross enrolment ratio of 50% in higher education, vocational education included, by 2035."),
 ("The National Assessment and Accreditation Council (NAAC) was established in:", ["1986", "1994", "2000", "2015"], "B",
  "1994, by the UGC, following the National Policy on Education of 1986. 2015 is the year NIRF was launched."),
 ("Indira Gandhi National Open University (IGNOU) was established in:", ["1962", "1982", "1985", "1992"], "C",
  "1985. 1962 is when Delhi University began correspondence courses, and 1982 when the first state open university was founded, in Andhra Pradesh."),
 ("Technical education in India is regulated by:", ["The UGC", "The NCTE", "The NAAC", "The AICTE"], "D",
  "The All India Council for Technical Education. NCTE regulates teacher education; NAAC accredits; the UGC sets university standards and gives grants."),
 ("The National Institutional Ranking Framework (NIRF):", ["Ranks higher education institutions each year", "Accredits colleges with grades", "Funds state universities", "Awards degrees"], "A",
  "NIRF ranks institutions annually. Accreditation with grades is NAAC's work; funding of state institutions is RUSA's."),
 ("Education was moved from the State List to the Concurrent List by:", ["The 42nd Amendment, 1976", "The 44th Amendment, 1978", "The 73rd Amendment, 1992", "The 86th Amendment, 2002"], "A",
  "The 42nd Amendment of 1976. The 86th Amendment of 2002 made elementary education a fundamental right."),
 ("In a university, the body responsible for courses, examinations and academic standards is the:", ["Executive Council", "Court", "Academic Council", "Finance Committee"], "C",
  "The Academic Council. The Executive Council (or Syndicate) handles administration and finance."),
 ("An institution is declared a deemed-to-be university under:", ["Section 3 of the UGC Act", "Article 30 of the Constitution", "Entry 66 of the Union List", "Section 12B of the UGC Act"], "A",
  "Section 3 of the UGC Act, 1956. Section 12B concerns eligibility for central grants; Article 30, the rights of minority institutions."),
 ("Which of these is an example of oriental learning?", ["A B.Tech. at an IIT", "An MBA by distance mode", "A diploma at a polytechnic", "An Acharya degree at a Sanskrit university"], "D",
  "Oriental learning keeps the classical traditions: Sanskrit, Pali, Persian, Arabic. The others are technical, management and distance programmes."),
 ("Which of these is a non-conventional programme?", ["A full-time B.Sc. in a college", "A correspondence M.A. from an open university", "A regular Ph.D. on campus", "A full-time LL.B."], "B",
  "Open and distance programmes break the conditions of conventional, full-time, on-campus study."),
 ("The National Skills Qualifications Framework (NSQF):", ["Ranks universities", "Funds research", "Replaces the UGC", "Arranges qualifications in levels by competence"], "D",
  "It organises qualifications in levels of knowledge, skill and aptitude, so that skills can be recognised, compared and built on."),
 ("The National Medical Commission replaced:", ["AICTE", "NCTE", "The Dental Council of India", "The Medical Council of India"], "D",
  "The National Medical Commission replaced the Medical Council of India in 2020."),
 ("The National Policy on Education of 1986 was revised in:", ["1990", "1992", "1998", "2005"], "B",
  "1992, with a Programme of Action."),
 ("Environmental studies became a compulsory part of education following the Supreme Court's directions in:", ["Kesavananda Bharati v. State of Kerala", "Maneka Gandhi v. Union of India", "M. C. Mehta v. Union of India", "Vishaka v. State of Rajasthan"], "C",
  "M. C. Mehta v. Union of India. The other cases concern the basic structure of the Constitution, personal liberty and sexual harassment at work."),
]

UNITS = [
 (1, "Teaching Aptitude", "Levels and objectives of teaching, learners, methods, SWAYAM, support systems, evaluation, CBCS.", U1),
 (2, "Research Aptitude", "Types and methods of research, positivism, steps, sampling, referencing, ICT, ethics.", U2),
 (3, "Comprehension", "Four passages, five questions each: main idea, detail, inference, vocabulary, tone.", U3),
 (4, "Communication", "Models, types, non-verbal cues, culture and groups, classroom talk, barriers, mass media.", U4),
 (5, "Mathematical Reasoning and Aptitude", "Reasoning, series, codes, directions, and the arithmetic: speed, percentages, profit, interest, averages.", U5),
 (6, "Logical Reasoning", "Syllogisms, argument forms, distribution, the square of opposition, fallacies, analogies, Indian logic.", U6),
 (7, "Data Interpretation", "Two data sets of five questions each, then sources and kinds of data, scales, charts and data governance.", U7), (8, "Information and Communication Technology", "Bits and bytes, protocols, internet, intranet, e-mail, conferencing, digital initiatives, e-governance.", U8),
 (9, "People, Development and Environment", "MDGs and SDGs, pollution and waste, pollutants and health, laws, the NAPCC, international agreements, disasters.", U9),
 (10, "Higher Education System", "Ancient centres, commissions and policies, regulators, kinds of programme, skills, value education, governance.", U10),
]
