# -*- coding: utf-8 -*-
"""Every ISS syllabus section mapped onto the pages that teach it.

Each row is (syllabus line, destination, grade).  The destination is None,
one html path, or a tuple of paths when the syllabus line spans two pages.
Grades: "deep"    a full unit page here, derivations and worked problems
        "brief"   covered at exam level
        "missing" nothing on this site teaches it
Destinations are written relative to statistics-papers/iss/.
"""
S = "../../statistics-major/"
M = S + "msc/"
EC = "../../exam-subjects/economics/"
N = "../../ugc-net-statistics/"
D = "../../data-science-major/"

def bsc(folder, unit):
    return f"{S}{folder}/unit{unit}_{folder}.html"

PAPERS = {
1: {
 "code": "STATISTICS-I", "type": "Objective", "marks": 200, "time": "2 hrs",
 "sections": [
  ("i", "Probability", [
   ("Classical and axiomatic definitions of probability and consequences; law of total probability, conditional probability, Bayes' theorem and applications",
    bsc("theory of probability", 1), "deep"),
   ("Discrete and continuous random variables; distribution functions and their properties",
    bsc("theory of probability", 2), "deep"),
   ("Standard discrete and continuous distributions &mdash; Bernoulli, uniform, binomial, Poisson, geometric, rectangular, exponential, normal, Cauchy, hypergeometric, multinomial, Laplace, negative binomial, beta, gamma, lognormal",
    (S + "theoretical discrete distributions/index_theoretical discrete distributions.html",
     S + "theoretical continuous distributions/index_theoretical continuous distributions.html"), "deep"),
   ("The same families with their generating functions, and the relations between them derived rather than tabulated",
    M + "distribution-theory/unit1.html", "deep"),
   ("Random vectors, joint and marginal distributions, conditional distributions, distributions of functions of random variables",
    bsc("theory of probability", 3), "deep"),
   ("Modes of convergence of sequences of random variables &mdash; in distribution, in probability, with probability one and in mean square",
    M + "probability-theory/unit3.html", "deep"),
   ("Mathematical expectation and conditional expectation",
    M + "probability-theory/unit2.html", "deep"),
   ("Characteristic function, moment and probability generating functions; inversion, uniqueness and continuity theorems",
    (M + "probability-theory/unit2.html", M + "probability-theory/unit4.html"), "deep"),
   ("Borel 0&ndash;1 law, Kolmogorov's 0&ndash;1 law; Tchebycheff's and Kolmogorov's inequalities",
    (M + "probability-theory/unit3.html", M + "probability-theory/unit2.html"), "deep"),
   ("Laws of large numbers and central limit theorems for independent variables",
    M + "probability-theory/unit4.html", "deep"),
   ("Order statistics &mdash; minimum, maximum, range and median",
    M + "distribution-theory/unit4.html", "deep"),
  ]),
  ("ii", "Statistical Methods", [
   ("Collection, compilation and presentation of data; charts, diagrams and histogram; frequency distribution",
    (bsc("descriptive statistics", 1), bsc("descriptive statistics", 2)), "deep"),
   ("Measures of location, dispersion, skewness and kurtosis",
    (bsc("descriptive statistics", 3), bsc("descriptive statistics", 4),
     bsc("descriptive statistics", 5)), "deep"),
   ("Bivariate and multivariate data; association and contingency",
    bsc("statistical methods", 5), "deep"),
   ("Curve fitting and orthogonal polynomials",
    bsc("statistical methods", 1), "deep"),
   ("Bivariate normal distribution", M + "multivariate-analysis/unit1.html", "deep"),
   ("Regression &mdash; linear, polynomial", bsc("statistical methods", 4), "deep"),
   ("Distribution of the correlation coefficient", M + "multivariate-analysis/unit2.html", "deep"),
   ("Partial and multiple correlation; intraclass correlation; correlation ratio",
    bsc("statistical methods", 3), "deep"),
   ("Standard errors and large sample tests", bsc("inferential statistics", 3), "deep"),
   ("Sampling distributions of sample mean, sample variance, t, chi-square and F; tests of significance based on them; small sample tests",
    bsc("inferential statistics", 4), "deep"),
   ("Non-parametric tests &mdash; goodness of fit, sign, median, run, Wilcoxon, Mann-Whitney, Wald-Wolfowitz and Kolmogorov-Smirnov",
    bsc("inferential statistics", 5), "deep"),
   ("Concept of asymptotic relative efficiency", None, "missing"),
  ]),
  ("iii", "Numerical Analysis", [
   ("Finite differences of different orders; &Delta;, E and D operators; factorial representation of a polynomial; separation of symbols; sub-division of intervals; differences of zero",
    None, "missing"),
   ("Interpolation and extrapolation: Newton&ndash;Gregory forward and backward formulae for equal intervals; formula for unequal intervals",
    None, "missing"),
   ("Central difference formulae due to Gauss, Stirling and Bessel; error terms in interpolation formulae",
    None, "missing"),
   ("Inverse interpolation and the different methods for it", None, "missing"),
   ("Numerical integration &mdash; Simpson's one-third and three-eighths rules, Weddle's rule",
    S + "actuarial statistics/practical_actuarial statistics.html", "brief"),
   ("Summation of series whose general term is a first difference, or in geometric progression",
    None, "missing"),
   ("Numerical solution of differential equations &mdash; Runge&ndash;Kutta method", None, "missing"),
  ]),
  ("iv", "Computer Application and Data Processing", [
   ("Basics of a computer: operations, central processing unit, memory, arithmetic and logical unit, input and output units; hardware and peripherals",
    D + "computer-fundamentals/index_computer-fundamentals.html", "brief"),
   ("Software, system and application software; number systems; operating systems; packages and utilities; low and high level languages; compiler, assembler; RAM, ROM, units of memory",
    D + "computer-fundamentals/index_computer-fundamentals.html", "brief"),
   ("Networks &mdash; LAN, WAN, internet, intranet; basics of computer security, virus, antivirus, firewall, spyware, malware",
    D + "computer-fundamentals/index_computer-fundamentals.html", "brief"),
   ("Algorithm, flowchart, data, information, database; overview of programming languages; front end and back end of a project",
    D + "dbms/index_dbms.html", "brief"),
   ("Variables, control structures, arrays and their usages, functions, modules, loops, conditional statements, exceptions, debugging",
    D + "python-data-structures/index_python-data-structures.html", "deep"),
  ]),
 ]},
2: {
 "code": "STATISTICS-II", "type": "Objective", "marks": 200, "time": "2 hrs",
 "sections": [
  ("i", "Linear Models", [
   ("Theory of linear estimation; Gauss&ndash;Markov linear models; estimable functions; error and estimation space",
    M + "linear-algebra-and-linear-models/unit4.html", "deep"),
   ("Normal equations and least square estimators; estimation of error variance; estimation with correlated observations; properties of least square estimators",
    M + "linear-algebra-and-linear-models/unit4.html", "deep"),
   ("Generalized inverse of a matrix and solution of normal equations; variances and covariances of least square estimators",
    (M + "linear-algebra-and-linear-models/unit1.html",
     M + "linear-algebra-and-linear-models/unit4.html"), "deep"),
   ("One-way and two-way classifications; fixed, random and mixed effects models",
    (M + "design-and-analysis-of-experiments/unit1.html", N + "unit3.html"), "brief"),
   ("Analysis of variance, two-way classification only",
    bsc("design and analysis of experiments", 1), "deep"),
   ("Multiple comparison tests due to Tukey, Scheff&eacute; and Student&ndash;Newman&ndash;Keuls&ndash;Duncan",
    M + "design-and-analysis-of-experiments/unit1.html", "deep"),
  ]),
  ("ii", "Statistical Inference and Hypothesis Testing", [
   ("Characteristics of a good estimator; estimation by maximum likelihood, minimum chi-square, moments and least squares; optimal properties of maximum likelihood estimators",
    M + "estimation-theory/unit2.html", "deep"),
   ("Minimum variance unbiased estimators; minimum variance bound estimators; Cram&eacute;r&ndash;Rao inequality; Bhattacharya bounds",
    M + "estimation-theory/unit1.html", "deep"),
   ("Sufficient estimator; factorization theorem; complete statistics; Rao&ndash;Blackwell theorem",
    M + "estimation-theory/unit1.html", "deep"),
   ("Confidence interval estimation; optimum confidence bounds",
    M + "estimation-theory/unit3.html", "deep"),
   ("Resampling, bootstrap and jackknife", M + "estimation-theory/unit2.html", "deep"),
   ("Hypothesis testing: simple and composite hypotheses; two kinds of error; critical region; power function",
    bsc("inferential statistics", 2), "deep"),
   ("Different types of critical regions and similar regions",
    M + "testing-of-hypotheses/unit2.html", "deep"),
   ("Most powerful and uniformly most powerful tests; Neyman&ndash;Pearson fundamental lemma",
    M + "testing-of-hypotheses/unit1.html", "deep"),
   ("Unbiased test; randomized test", M + "testing-of-hypotheses/unit2.html", "deep"),
   ("Likelihood ratio test", M + "testing-of-hypotheses/unit3.html", "deep"),
   ("Wald's SPRT, OC and ASN functions", M + "testing-of-hypotheses/unit4.html", "deep"),
   ("Elements of decision theory", M + "estimation-theory/unit4.html", "deep"),
  ]),
  ("iii", "Official Statistics", [
   ("Official statistics: need, uses, users, reliability, relevance, limitations, transparency, visibility",
    None, "missing"),
   ("Compilation, collection, processing, analysis and dissemination; agencies involved; methods",
    None, "missing"),
   ("National Statistical Organization: vision and mission; NSSO and CSO, roles and responsibilities, activities and publications",
    N + "unit10.html", "brief"),
   ("National Statistical Commission: need, constitution, role and functions; legal acts and provisions for official statistics",
    N + "unit10.html", "brief"),
   ("Index numbers: types, need, data collection mechanism, periodicity, agencies involved, uses",
    bsc("applied statistics", 3), "deep"),
   ("Sector-wise statistics &mdash; agriculture, health, education, women and child; important surveys and censuses, indicators, agencies",
    None, "missing"),
   ("National accounts: definition, basic concepts, issues, strategy, collection of data and release",
    EC + "unit2.html", "brief"),
   ("Population census: need, data collected, periodicity, methods of collection, dissemination, agencies",
    bsc("applied statistics", 4), "brief"),
   ("Socio-economic indicators; gender awareness and statistics", None, "missing"),
  ]),
 ]},
3: {
 "code": "STATISTICS-III", "type": "Descriptive", "marks": 200, "time": "3 hrs",
 "sections": [
  ("i", "Sampling Techniques", [
   ("Population and sample; need for sampling; complete enumeration versus sampling; basic concepts; sampling and non-sampling error",
    bsc("sampling techniques", 1), "deep"),
   ("Methodologies in sample surveys &mdash; questionnaires, sampling design and field investigation as followed by NSSO",
    None, "missing"),
   ("Subjective or purposive sampling; probability sampling; simple random sampling with and without replacement; estimation of population mean and proportion and their standard errors",
    bsc("sampling techniques", 2), "deep"),
   ("Stratified random sampling; proportional and optimum allocation; comparison with simple random sampling for fixed sample size",
    bsc("sampling techniques", 3), "deep"),
   ("Ratio, product and regression methods of estimation; bias and variance to the first order of approximation; comparison with simple random sampling",
    M + "sampling-theory/unit2.html", "deep"),
   ("Systematic sampling when N is an integer multiple of n; estimation of the mean and its standard error; comparison with simple random sampling",
    bsc("sampling techniques", 4), "deep"),
   ("Sampling with probability proportional to size, with and without replacement; Horvitz&ndash;Thompson estimator",
    M + "sampling-theory/unit1.html", "deep"),
   ("Des Raj and Das estimators for n = 2", None, "missing"),
   ("Equal size cluster sampling: estimators of the mean and total and their standard errors; comparison with SRS through the intra-class correlation coefficient",
    M + "sampling-theory/unit3.html", "deep"),
   ("Multistage sampling; two-stage sampling with equal second-stage units; estimation of the mean and total",
    M + "sampling-theory/unit4.html", "deep"),
   ("Double sampling in ratio and regression methods of estimation", N + "unit3.html", "brief"),
   ("Interpenetrating sub-sampling", None, "missing"),
  ]),
  ("ii", "Econometrics", [
   ("Nature of econometrics; the general linear model and its extensions; ordinary least squares estimation and prediction",
    (bsc("econometrics", 1), bsc("econometrics", 2)), "deep"),
   ("Generalized least squares estimation and prediction; heteroscedastic disturbances; pure and mixed estimation",
    bsc("econometrics", 3), "brief"),
   ("Autocorrelation, its consequences and tests; Theil BLUS procedure, estimation and prediction",
    bsc("econometrics", 5), "brief"),
   ("Multicollinearity, its implications and tools for handling it; ridge regression",
    bsc("econometrics", 4), "deep"),
   ("Linear and stochastic regression; instrumental variable estimation; errors in variables; autoregressive lag model",
    (bsc("econometrics", 3), bsc("econometrics", 5)), "brief"),
   ("Simultaneous linear equations model and its generalization; identification problem; restrictions on structural parameters; rank and order conditions",
    (bsc("econometrics", 5), N + "unit6.html"), "brief"),
   ("Estimation in simultaneous equations models; recursive systems; 2SLS, limited information, k-class, 3SLS and full information maximum likelihood estimators; prediction and simultaneous confidence intervals",
    bsc("econometrics", 5), "brief"),
  ]),
  ("iii", "Applied Statistics", [
   ("Index numbers: price and quantity relatives; link and chain relatives; Laspeyres, Paasche, Marshall&ndash;Edgeworth and Fisher index numbers; chain base index numbers; tests for index numbers",
    bsc("applied statistics", 3), "deep"),
   ("Construction of index numbers of wholesale and consumer prices",
    bsc("applied statistics ii", 2), "deep"),
   ("Income distribution &mdash; Pareto and Engel curves; concentration curve",
    (bsc("applied statistics ii", 3), bsc("descriptive statistics", 4)), "brief"),
   ("Methods of estimating national income; inter-sectoral flows; inter-industry table; role of CSO",
    EC + "unit2.html", "deep"),
   ("Demand analysis", bsc("applied statistics ii", 3), "deep"),
   ("Economic time series: components, additive and multiplicative models; determination of trend, seasonal and cyclical fluctuations",
    bsc("applied statistics", 1), "deep"),
   ("Time series as a discrete parameter stochastic process; autocovariance and autocorrelation functions and their properties",
    N + "unit7.html", "brief"),
   ("Exploratory time series analysis; tests for trend and seasonality; exponential and moving average smoothing; Holt and Winters smoothing; forecasting based on smoothing",
    bsc("applied statistics", 2), "brief"),
   ("Stationary processes: moving average, autoregressive, ARMA and ARIMA models; Box&ndash;Jenkins models; choice of AR and MA orders",
    D + "data-science-r/arima-forecasting-in-r.html", "brief"),
   ("Estimation of the mean, autocovariance and autocorrelation functions under large sample theory; estimation of ARIMA parameters",
    None, "missing"),
   ("Spectral analysis of weakly stationary processes; periodogram and correlogram analyses; computations based on the Fourier transform",
    None, "missing"),
  ]),
 ]},
4: {
 "code": "STATISTICS-IV", "type": "Descriptive", "marks": 200, "time": "3 hrs",
 "sections": [
  ("i", "Operations Research and Reliability", [
   ("Definition and scope of operations research; phases; models and their solutions; decision-making under uncertainty and risk; different criteria; sensitivity analysis",
    bsc("operations research", 1), "brief"),
   ("Dynamic programming and its application to linear programming problems",
    None, "missing"),
   ("Two-person games, pure and mixed strategies; existence and uniqueness of the value in zero-sum games; solutions of 2&times;2, 2&times;m and m&times;n games",
    bsc("optimization techniques", 4), "deep"),
   ("Inventory problems; the EOQ formula of Harris, its sensitivity analysis and extensions with quantity discounts and shortages; multi-item inventory subject to constraints; models with random demand; P and Q systems",
    None, "missing"),
   ("Queuing models and effectiveness measures; steady-state M/M/1 and M/M/c with queue-length and waiting-time distributions; M/G/1 and the Pollaczek&ndash;Khinchine result",
    N + "unit9.html", "brief"),
   ("Sequencing and scheduling; 2-machine n-job and 3-machine n-job problems; branch and bound for the travelling salesman problem",
    (bsc("optimization techniques", 3), bsc("optimization techniques", 2)), "deep"),
   ("Replacement problems &mdash; block and age replacement policies", None, "missing"),
   ("PERT and CPM; probability of project completion", bsc("optimization techniques", 5), "deep"),
   ("Reliability concepts and measures; components and systems; coherent systems and their reliability",
    None, "missing"),
   ("Life distributions, reliability function, hazard rate; exponential, Weibull and gamma life distributions; bivariate exponential; estimation and tests in these models",
    (S + "advanced actuarial statistics/unit1_advanced actuarial statistics.html",
     S + "theoretical continuous distributions/unit2_theoretical continuous distributions.html"), "brief"),
   ("Notions of ageing &mdash; IFR, IFRA, NBU, DMRL and NBUE classes and their duals; loss of memory property of the exponential",
    None, "missing"),
   ("Reliability estimation from censored life tests and tests with replacement; stress&ndash;strength reliability and its estimation",
    None, "missing"),
  ]),
  ("ii", "Demography and Vital Statistics", [
   ("Sources of demographic data &mdash; census, registration, ad-hoc surveys, hospital records; demographic profiles of the Indian census",
    bsc("applied statistics", 4), "deep"),
   ("Complete life table and its main features; uses of a life table",
    bsc("applied statistics", 5), "deep"),
   ("Makeham's and Gompertz's curves; national life tables; UN model life tables; abridged life tables",
    (S + "advanced actuarial statistics/unit1_advanced actuarial statistics.html",
     S + "actuarial statistics/unit3_actuarial statistics.html"), "brief"),
   ("Stable and stationary populations", bsc("applied statistics", 5), "brief"),
   ("Measurement of fertility &mdash; crude birth rate, general fertility rate, age-specific birth rate, total fertility rate, gross and net reproduction rates",
    bsc("applied statistics", 5), "deep"),
   ("Measurement of mortality &mdash; crude death rate, standardized death rates, age-specific death rates, infant mortality rate, death rate by cause",
    bsc("applied statistics", 4), "deep"),
   ("Internal migration and its measurement; migration models; international migration; net migration",
    None, "missing"),
   ("Inter-censal and post-censal estimates; projection methods including logistic curve fitting; the decennial census in India",
    bsc("applied statistics ii", 1), "brief"),
  ]),
  ("iii", "Survival Analysis and Clinical Trial", [
   ("Time, order and random censoring; likelihood in these cases; exponential, gamma, Weibull, lognormal, Pareto and linear failure rate distributions and inference for them",
    (S + "statistical analysis of clinical trials/unit4.html",
     S + "theoretical continuous distributions/unit2_theoretical continuous distributions.html"), "brief"),
   ("Life tables, failure rate, mean residual life and their elementary classes and properties",
    S + "actuarial statistics/unit3_actuarial statistics.html", "brief"),
   ("Estimation of the survival function &mdash; actuarial estimator, Kaplan&ndash;Meier estimator; estimation under IFR or DFR; tests of exponentiality against non-parametric classes; total time on test",
    S + "statistical analysis of clinical trials/unit4.html", "deep"),
   ("Two-sample problem &mdash; Gehan test, log-rank test; semi-parametric regression for the failure rate; rank test for the regression coefficient",
    S + "statistical analysis of clinical trials/unit4.html", "deep"),
   ("Competing risk model; parametric and non-parametric inference for it", None, "missing"),
   ("Introduction to clinical trials: need and ethics; bias and random error; conduct of trials; Phase I to IV; multicentre trials",
    S + "statistical analysis of clinical trials/unit1.html", "deep"),
   ("Data management &mdash; data definitions, case report forms, database design, data collection systems for good clinical practice",
    S + "statistical analysis of clinical trials/unit1.html", "brief"),
   ("Design of clinical trials: parallel versus cross-over, cross-sectional versus longitudinal, factorial designs; objectives and endpoints; Phase I, II and III designs with sequential stopping",
    (S + "statistical analysis of clinical trials/unit3.html",
     S + "statistical analysis of clinical trials/unit2.html"), "deep"),
   ("Reporting and analysis &mdash; categorical outcomes from Phase I to III trials; analysis of survival data",
    S + "statistical analysis of clinical trials/unit4.html", "deep"),
  ]),
  ("iv", "Quality Control", [
   ("Quality of a product; need for quality control; basic concepts of process control, process capability and product control",
    S + "statistical quality control/unit1.html", "deep"),
   ("General theory of control charts; causes of variation; control limits; sub-grouping; summary of out-of-control criteria",
    S + "statistical quality control/unit1.html", "deep"),
   ("Charts for attributes &mdash; p, np, c and u charts", S + "statistical quality control/unit3.html", "deep"),
   ("Charts for variables &mdash; X-bar and R, X-bar and s charts",
    S + "statistical quality control/unit2.html", "deep"),
   ("Process capability and process optimization", S + "statistical quality control/unit2.html", "deep"),
   ("OC and ARL of control charts; control by gauging; moving average and exponentially weighted moving average charts; Cu-Sum charts with V-masks and decision intervals; economic design of the X-bar chart",
    None, "missing"),
   ("Acceptance sampling plans for attributes &mdash; single and double sampling plans and their properties",
    (S + "statistical quality control/unit4.html", S + "statistical quality control/unit5.html"), "deep"),
   ("Plans for inspection by variables for one-sided and two-sided specifications", None, "missing"),
  ]),
  ("v", "Multivariate Analysis", [
   ("Multivariate normal distribution and its properties; random sampling from it; maximum likelihood estimators of the parameters",
    M + "multivariate-analysis/unit1.html", "deep"),
   ("Distribution of the sample mean vector; Wishart matrix and its distribution and properties",
    M + "multivariate-analysis/unit2.html", "deep"),
   ("Distribution of the sample generalized variance; null and non-null distribution of simple correlation coefficients",
    M + "multivariate-analysis/unit2.html", "deep"),
   ("Null distribution of partial and multiple correlation coefficients; distribution of the sample regression coefficients",
    M + "multivariate-analysis/unit2.html", "deep"),
   ("Hotelling's T-squared and its applications; Mahalanobis D-squared; classification and discrimination procedures",
    M + "multivariate-analysis/unit3.html", "deep"),
   ("Principal component analysis; canonical variates and canonical correlation &mdash; definition, use, estimation and computation",
    M + "multivariate-analysis/unit4.html", "deep"),
  ]),
  ("vi", "Design and Analysis of Experiments", [
   ("Analysis of variance for one-way and two-way classifications; need for design of experiments; basic principles of experimental design",
    bsc("design and analysis of experiments", 1), "deep"),
   ("Completely randomized, randomized block and Latin square designs; their analyses and efficiencies",
    (bsc("design and analysis of experiments", 2),
     bsc("design and analysis of experiments", 3),
     bsc("design and analysis of experiments", 4)), "deep"),
   ("Factorial experiments and confounding in 2-level and 3-level experiments",
    (M + "design-and-analysis-of-experiments/unit2.html",
     M + "design-and-analysis-of-experiments/unit3.html"), "deep"),
   ("Analysis of covariance", M + "design-and-analysis-of-experiments/unit1.html", "deep"),
   ("Analysis of non-orthogonal data", M + "design-and-analysis-of-experiments/unit1.html", "deep"),
   ("Analysis of missing data", bsc("design and analysis of experiments", 5), "deep"),
  ]),
  ("vii", "Computing with C and R", [
   ("Basics of C: components, structure of a program, data types, enumerated and derived types",
    D + "problem-solving-c/index_problem-solving-c.html", "deep"),
   ("Operators, control structures, arrays, functions, pointers, structures and file handling in C",
    D + "problem-solving-c/index_problem-solving-c.html", "deep"),
   ("Basics of R: the environment, objects, vectors, matrices, lists and data frames; import and export",
    S + "computational statistics and r programming/unit1_computational statistics and r programming.html", "deep"),
   ("Descriptive statistics and graphics in R",
    S + "computational statistics and r programming/unit2_computational statistics and r programming.html", "deep"),
   ("Statistical tests, correlation and regression in R",
    S + "computational statistics and r programming/unit4_computational statistics and r programming.html", "deep"),
   ("Building statistical programs in R without packages, and writing a statistical report",
    M + "data-handling-using-r/practical.html", "deep"),
  ]),
 ]},
}
