#!/usr/bin/env python3
"""Put one navigation on every page, and take the other three away.

    python3 tools/add_site_nav.py            # dry run
    python3 tools/add_site_nav.py --apply    # write

WHY. 675 of the 691 pages had no route to the rest of the site. Four different
patterns were doing the job between them -- a site bar on 17 pages, a sticky
13-link row on the UGC NET pages, a breadcrumb on 642 that only ever reached
the page's own folder, and 23 pages with nothing at all -- and not one page
carried aria-current or a skip link.

NO JAVASCRIPT. The menu is <details>/<summary>, which the site already uses
1,829 times, so this is the house mechanism rather than a new dependency. That
means click-to-open, which is the right interaction on the phones most of these
readers use anyway: a hover menu has no touch equivalent. It also means the
menu still works when a script fails, which a site whose whole appeal is
loading fast on a phone should care about.

WHAT IT REPLACES.
  * the .nrstatlab-bar on 17 pages -- the new bar says everything it said;
  * the UGC NET sticky <nav class="topnav">, 13 links that wrapped to three
    rows and ate ~120px of a 400px viewport. Nothing is lost: those 13 pages
    are listed inside the Examinations menu, which costs no vertical space
    until a reader opens it.
The breadcrumb stays. It answers a different question -- where am I -- and it
is the only thing that does.

The menu itself is in site_nav_model.py, built from the tree, with every label
read from the destination page's own <title>.

Idempotent: a second --apply reports 0 changed.
"""
import argparse
import pathlib
import posixpath
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from site_nav_model import menu, PLAIN          # noqa: E402
from stubs import is_stub                       # noqa: E402

START = "<!-- site-nav: generated by tools/add_site_nav.py, do not edit here -->"
END = "<!-- /site-nav -->"
CSS_HREF = "assets/site-nav.css"

BODY = re.compile(r"<body[^>]*>")
HEAD_END = re.compile(r"</head>")
# The leading \n? matters: the block is inserted as "\n" + block, so a strip
# that only ate the trailing newline left one behind and the file grew a
# blank line on every run -- which is exactly the way "idempotent" quietly
# stops being true.
BLOCK = re.compile(r"\n?" + re.escape(START) + r".*?" + re.escape(END) + r"\n?", re.S)
CSS_LINK = re.compile(r'[ \t]*<link rel="stylesheet" href="[^"]*' + re.escape(CSS_HREF) + r'">\n?')
# The two navigations this one replaces.
OLD_BAR = re.compile(r'[ \t]*<div class="nrstatlab-bar">.*?</div></div>\n?', re.S)
OLD_TOPNAV = re.compile(r'[ \t]*<nav class="topnav">.*?</nav>\n?', re.S)


def rel(page_dir, target):
    """Target, as this page must write it."""
    return posixpath.relpath(target, page_dir) if page_dir else target


def render(page_dir, page_rel):
    """The nav block for one page, with aria-current on the row that is it."""
    def a(label, href, cls=""):
        cur = ' aria-current="page"' if href == page_rel else ""
        c = f' class="{cls}"' if cls else ""
        return f'<a{c} href="{rel(page_dir, href)}"{cur}>{label}</a>'

    out = [START,
           '<a class="nav-skip" href="#nrstat-content">Skip to the content</a>',
           '<nav class="sitenav" aria-label="Site">',
           '  <div class="sitenav-in">',
           f'    {a("NRSTATLAB", "index.html", "sitenav-brand")}']
    for top, hub, groups in menu():
        out.append('    <details class="sitenav-menu">')
        out.append(f'      <summary>{top}</summary>')
        out.append('      <div class="sitenav-panel">')
        if hub:
            out.append(f'        {a("All of " + top, hub, "sitenav-all")}')
        for gname, rows in groups:
            if gname:
                out.append(f'        <p class="sitenav-group">{gname}</p>')
            for label, href in rows:
                out.append(f'        {a(label, href)}')
        out.append('      </div>')
        out.append('    </details>')
    for label, href in PLAIN:
        out.append(f'    {a(label, href, "sitenav-plain")}')
    out += ['  </div>', '</nav>',
            '<div id="nrstat-content" tabindex="-1"></div>', END]
    return "\n".join(out) + "\n"


def pages():
    for p in sorted(ROOT.rglob("*.html")):
        if ".git" in p.parts or "archive" in p.parts:
            continue
        if is_stub(p):                 # a stub is not a page a reader stays on
            continue
        yield p


def rewrite(path):
    text = path.read_text(errors="replace")
    page_rel = path.relative_to(ROOT).as_posix()
    page_dir = posixpath.dirname(page_rel)

    out = BLOCK.sub("", text)          # so a re-run replaces rather than stacks
    out = CSS_LINK.sub("", out)
    removed = []
    out, n = OLD_BAR.subn("", out)
    if n:
        removed.append("site bar")
    out, n = OLD_TOPNAV.subn("", out)
    if n:
        removed.append("sticky unit row")

    m = HEAD_END.search(out)
    if not m:
        return None, "NO </head>"
    link = f'<link rel="stylesheet" href="{rel(page_dir, CSS_HREF)}">\n'
    out = out[:m.start()] + link + out[m.start():]

    m = BODY.search(out)
    if not m:
        return None, "NO <body>"
    out = out[:m.end()] + "\n" + render(page_dir, page_rel) + out[m.end():]

    note = "nav"
    if removed:
        note += " (-" + ", -".join(removed) + ")"
    return (out if out != text else None), note


def main(apply_changes):
    changed, removed_bar, removed_nav, problems = 0, 0, 0 , []
    n = 0
    for p in pages():
        n += 1
        new, note = rewrite(p)
        if note.startswith("NO "):
            problems.append(f"{p.relative_to(ROOT)}: {note}")
            continue
        if new is None:
            continue
        changed += 1
        removed_bar += "site bar" in note
        removed_nav += "sticky unit row" in note
        if apply_changes:
            p.write_text(new)
    print(f"{n} pages, {changed} changed")
    print(f"   {removed_bar} lost the old site bar, "
          f"{removed_nav} lost the sticky unit row")
    for pr in problems:
        print("   SKIPPED", pr)
    if not apply_changes:
        print("dry run -- pass --apply to write")
    return 1 if problems else 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    sys.exit(main(ap.parse_args().apply))
