#!/usr/bin/env python3
"""Write the site's shared chrome into every page: navigation, footer, head tags.

Started as the navigation alone -- hence the name -- and now writes everything
that must be identical on all 691 pages and would drift if kept by hand:

  * the navigation bar (below);
  * one site footer: About, Report an error, Licence, Topics A-Z, and the date
    the page's CONTENT last changed (tools/content_dates.py -- not the date the
    file was last touched, which after a site-wide change is every page's);
  * in <head>: the shared stylesheets, the favicon links, and the share-card
    tags (og:image), which no page had -- a link shared in WhatsApp or Telegram
    arrived as a grey box.

Put one navigation on every page, and take the other three away.

    python3 tools/add_site_nav.py            # dry run
    python3 tools/add_site_nav.py --apply    # write

WHY. 675 of the 691 pages had no route to the rest of the site. Four different
patterns were doing the job between them -- a site bar on 17 pages, a sticky
13-link row on the UGC NET pages, a breadcrumb on 642 that only ever reached
the page's own folder, and 23 pages with nothing at all -- and not one page
carried aria-current or a skip link.

NO JAVASCRIPT. The menu is <details>/<summary>, which the site already uses
1,829 times, so this is the house mechanism rather than a new dependency. That
means click-to-open, which is the right interaction on the phones most of these
readers use anyway: a hover menu has no touch equivalent. It also means the
menu still works when a script fails, which a site whose whole appeal is
loading fast on a phone should care about.

WHAT IT REPLACES.
  * the .nrstatlab-bar on 17 pages -- the new bar says everything it said;
  * the UGC NET sticky <nav class="topnav">, 13 links that wrapped to three
    rows and ate ~120px of a 400px viewport. Nothing is lost: those 13 pages
    are listed inside the Examinations menu, which costs no vertical space
    until a reader opens it.
The breadcrumb stays. It answers a different question -- where am I -- and it
is the only thing that does.

The menu itself is in site_nav_model.py, built from the tree, with every label
read from the destination page's own <title>.

Idempotent: a second --apply reports 0 changed.
"""
import argparse
import pathlib
import posixpath
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from site_nav_model import menu, PLAIN          # noqa: E402
from stubs import is_stub                       # noqa: E402
from content_dates import content_dates         # noqa: E402
import datetime                                 # noqa: E402
import html as html_mod                         # noqa: E402
from urllib.parse import urlparse               # noqa: E402

SITE_BASE = "https://nrstatlab.github.io/planning-for-future"
# The site's path on its host, "/planning-for-future/" today and "/" after a
# move to its own domain. It must agree with SITE_BASE in build_site.py, and
# check_site_nav.js fails if a page's favicon or share card does not resolve.
BASE_PATH = urlparse(SITE_BASE).path.rstrip("/") + "/"

# Student lab exercises: each one IS a page of the student's own HTML, shown
# as the exercise produces it. Wrapping them in the site's bar changes the
# thing they exist to show.
EXCLUDE = ("data-science/labs/",)

START = "<!-- site-nav: generated by tools/add_site_nav.py, do not edit here -->"
END = "<!-- /site-nav -->"
HSTART = "<!-- site-head: generated by tools/add_site_nav.py -->"
HEND = "<!-- /site-head -->"
FSTART = "<!-- site-foot: generated by tools/add_site_nav.py -->"
FEND = "<!-- /site-foot -->"
CSS_HREF = "assets/site-nav.css"

BODY = re.compile(r"<body[^>]*>")
HEAD_END = re.compile(r"</head>")
# The leading \n? matters: the block is inserted as "\n" + block, so a strip
# that only ate the trailing newline left one behind and the file grew a
# blank line on every run -- which is exactly the way "idempotent" quietly
# stops being true.
BLOCK = re.compile(r"\n?" + re.escape(START) + r".*?" + re.escape(END) + r"\n?", re.S)
CSS_LINK = re.compile(r'[ \t]*<link rel="stylesheet" href="[^"]*' + re.escape(CSS_HREF) + r'">\n?')
# The two navigations this one replaces.
# Each strip pattern mirrors how its block is inserted -- head as block+"\n"
# before </head>, foot as "\n"+block+"\n" before </body> -- so a strip and
# a re-insert give back the same bytes.
HBLOCK = re.compile(re.escape(HSTART) + r".*?" + re.escape(HEND) + r"\n?", re.S)
FBLOCK = re.compile(r"\n?" + re.escape(FSTART) + r".*?" + re.escape(FEND) + r"\n?", re.S)
BODY_END = re.compile(r"</body>")
TWITTER = re.compile(r'<meta name="twitter:card" content="summary">')
# Footers that said only "this is NRSTATLAB" -- the site footer says it now.
# Page footers that say something about the page (a unit's name, the notice a
# map quotes) are content and are kept.
GENERIC_FOOT = re.compile(
    r'[ \t]*<footer>\s*(?:<div class="wrap">\s*<span><b>NRSTATLAB</b> (?:\u2014|&mdash;) '
    r'study material for statistics and data science</span>.*?</div>\s*'
    r'|NRSTATLAB\s*)</footer>\n?', re.S)
EMPTY_FOOT = re.compile(r'[ \t]*<footer>\s*</footer>\n?')
OLD_BAR = re.compile(r'[ \t]*<div class="nrstatlab-bar">.*?</div></div>\n?', re.S)
OLD_TOPNAV = re.compile(r'[ \t]*<nav class="topnav">.*?</nav>\n?', re.S)


def rel(page_dir, target):
    """Target, as this page must write it.

    page_dir is None for 404.html: GitHub Pages serves it for a missing URL at
    ANY depth, with the address bar still showing that URL, so no relative
    path is right from all of them. It gets root-absolute paths instead, built
    from SITE_BASE so a move to a custom domain still needs one edit. (The
    first version of the navigation wrote relative ones here, and a missing
    page two folders down showed an unstyled bar of broken links.)
    """
    if page_dir is None:
        return BASE_PATH + target
    return posixpath.relpath(target, page_dir) if page_dir else target


SEARCH_ICON = ('<svg class="sitenav-icon" viewBox="0 0 24 24" width="16" height="16" '
               'aria-hidden="true" focusable="false"><circle cx="10.5" cy="10.5" r="6.5" '
               'fill="none" stroke="currentColor" stroke-width="2.2"/><path d="M15.5 15.5 21 21" '
               'stroke="currentColor" stroke-width="2.2" stroke-linecap="round"/></svg>')


def base_of(page_dir):
    """What a page prefixes to a root-relative path: "", "../../", or BASE_PATH."""
    if page_dir is None:
        return BASE_PATH
    return "../" * (page_dir.count("/") + 1) if page_dir else ""


def render_search(page_dir):
    """Site-wide search, in the bar, on every page that has no box of its own.

    Only three pages had search at all; a reader on any of the other 688 had to
    go home to use it. This is the same box, driven by the same assets/search.js
    -- which fetches its index only when someone first types, so a page that is
    merely read pays nothing for it. The box ships hidden and the script
    un-hides it; with JavaScript off the menu still opens, on the A-Z index.

    type="text" with inputmode="search", not type="search": the HTML validator
    CI runs rejects role="combobox" on a search input, and the combobox role is
    what tells a screen reader that the list below the box belongs to it. No
    enterkeyhint either: that validator predates it and fails the page.
    """
    r = lambda t: rel(page_dir, t)          # noqa: E731
    return [
        '    <details class="sitenav-menu sitenav-search">',
        f'      <summary>{SEARCH_ICON}<span>Search</span></summary>',
        '      <div class="sitenav-panel">',
        '        <div class="search" hidden>',
        '          <label class="sr-head" for="nav-q">Search NRSTATLAB</label>',
        '          <input id="nav-q" type="text" inputmode="search"',
        '                 autocomplete="off" spellcheck="false"',
        '                 placeholder="Search the whole site &mdash; try &ldquo;chi square&rdquo;"',
        f'                 data-index="{r("assets/search-index.json")}" data-base="{base_of(page_dir)}"',
        '                 role="combobox" aria-expanded="false" aria-controls="nav-results"',
        '                 aria-autocomplete="list">',
        '          <ul id="nav-results" class="results" role="listbox"',
        '              aria-label="Search results" hidden></ul>',
        '          <p class="sstatus sr-head" role="status"></p>',
        '        </div>',
        f'        <a class="sitenav-az" href="{r("topics.html")}">Browse all topics A&ndash;Z</a>',
        '      </div>',
        '    </details>',
    ]


def render(page_dir, page_rel, own_search=False):
    """The nav block for one page, with aria-current on the row that is it."""
    def a(label, href, cls=""):
        cur = ' aria-current="page"' if href == page_rel else ""
        c = f' class="{cls}"' if cls else ""
        return f'<a{c} href="{rel(page_dir, href)}"{cur}>{label}</a>'

    out = [START,
           '<a class="nav-skip" href="#nrstat-content">Skip to the content</a>',
           '<nav class="sitenav" aria-label="Site">',
           '  <div class="sitenav-in">',
           f'    {a("NRSTATLAB", "index.html", "sitenav-brand")}']
    for top, hub, groups in menu():
        out.append('    <details class="sitenav-menu">')
        out.append(f'      <summary>{top}</summary>')
        out.append('      <div class="sitenav-panel">')
        if hub:
            out.append(f'        {a("All of " + top, hub, "sitenav-all")}')
        for gname, rows in groups:
            if gname:
                out.append(f'        <p class="sitenav-group">{gname}</p>')
            for label, href in rows:
                out.append(f'        {a(label, href)}')
        out.append('      </div>')
        out.append('    </details>')
    for label, href in PLAIN:
        out.append(f'    {a(label, href, "sitenav-plain")}')
    if not own_search:
        out += render_search(page_dir)
    out += ['  </div>', '</nav>',
            '<div id="nrstat-content" tabindex="-1"></div>', END]
    return "\n".join(out) + "\n"


# Stylesheets every page links, in cascade order, after its own section sheet.
SHEETS = ["assets/site-base.css", "assets/site-nav.css"]


def render_head(page_dir, own_search=False):
    """Shared <head> tags: stylesheets, favicon, share card, the search script."""
    r = lambda t: rel(page_dir, t)          # noqa: E731
    out = [HSTART]
    out += [f'<link rel="stylesheet" href="{r(h)}">' for h in SHEETS]
    if not own_search:          # the three pages with their own box load it already
        out.append(f'<script src="{r("assets/search.js")}" defer></script>')
    out += [
        f'<link rel="icon" href="{r("favicon.svg")}" type="image/svg+xml">',
        f'<link rel="icon" href="{r("favicon.png")}" type="image/png" sizes="32x32">',
        f'<link rel="icon" href="{r("favicon.ico")}" sizes="any">',
        # og:image must be absolute: a preview is fetched by a crawler that
        # has no page to resolve a relative path against.
        f'<meta property="og:image" content="{SITE_BASE}/assets/og-card.jpg">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        '<meta property="og:image:alt" content="NRSTATLAB — Statistics, Data Science '
        'and Machine Learning, written to teach.">',
        HEND,
    ]
    return "\n".join(out) + "\n"


def human_date(iso):
    d = datetime.date.fromisoformat(iso)
    return f"{d.day} {d.strftime('%B %Y')}"


def render_foot(page_dir, updated):
    r = lambda t: rel(page_dir, t)          # noqa: E731
    return "\n".join([
        FSTART,
        '<footer class="sitefoot">',
        '  <div class="sitefoot-in">',
        f'    <p class="sitefoot-brand"><a href="{r("index.html")}">NRSTATLAB</a> '
        '&mdash; study material for statistics and data science. Free to read, no sign-in.</p>',
        '    <nav class="sitefoot-links" aria-label="Site footer">',
        f'      <a href="{r("about.html")}">About</a>',
        # To the About page, not straight to GitHub: the house rule
        # (audit_content.py) is that a study page is never a doorway into a
        # code host, and About is the one page that explains what an issue is
        # and what to put in it before sending the reader there.
        f'      <a href="{r("about.html")}#report">Report an error</a>',
        f'      <a href="{r("about.html")}#licence">Licence: CC BY-NC-SA 4.0</a>',
        f'      <a href="{r("topics.html")}">Topics A&ndash;Z</a>',
        '    </nav>',
        f'    <p class="sitefoot-date">Content last updated '
        f'<time datetime="{updated}">{human_date(updated)}</time></p>',
        '  </div>',
        '</footer>',
        FEND,
    ]) + "\n"


COMMENT = re.compile(r"<!--.*?-->", re.S)


def find_tag(rx, text, last=False):
    """The first (or last) match of rx that is not inside an HTML comment.

    Seven pages -- the section hubs -- carry a comment in their <head> that
    says a block is "valid as a child of <body>". The first version of this
    tool matched that, put the navigation inside the comment, and the page
    showed a stray ". -->" under the bar while the bar itself rendered by luck.
    """
    masked = COMMENT.sub(lambda m: " " * len(m.group(0)), text)
    hits = list(rx.finditer(masked))
    if not hits:
        return None
    return hits[-1] if last else hits[0]


def excluded(page_rel):
    return page_rel.startswith(EXCLUDE)


def pages():
    for p in sorted(ROOT.rglob("*.html")):
        if ".git" in p.parts or "archive" in p.parts:
            continue
        if is_stub(p):                 # a stub is not a page a reader stays on
            continue
        yield p


def strip_chrome(text):
    """Everything this tool ever wrote, removed -- so a run replaces, not stacks."""
    out = BLOCK.sub("", text)
    out = FBLOCK.sub("", out)
    out = CSS_LINK.sub("", out)
    return out


def rewrite(path, updated):
    text = path.read_text(errors="replace")
    page_rel = path.relative_to(ROOT).as_posix()
    page_dir = None if page_rel == "404.html" else posixpath.dirname(page_rel)

    out = strip_chrome(text)
    # A page with its own search box (home, A-Z, the test chooser) keeps it,
    # and gets no second one: search.js drives the first box it finds.
    own_search = bool(re.search(r'<div class="search"', out))
    if excluded(page_rel):
        out = HBLOCK.sub("", out)
        return (out if out != text else None), "excluded"

    removed = []
    for rx, what in ((OLD_BAR, "site bar"), (OLD_TOPNAV, "sticky unit row"),
                     (GENERIC_FOOT, "generic footer"), (EMPTY_FOOT, "empty footer")):
        out, n = rx.subn("", out)
        if n:
            removed.append(what)
    out = TWITTER.sub('<meta name="twitter:card" content="summary_large_image">', out)

    # Put the head block back where it was, if it was there. check_canonical.py
    # also inserts before </head>, so always inserting there made the two
    # tags swap places depending on which tool ran last -- a diff on 8 pages
    # every time either was run on its own.
    anchor = "\x00site-head\x00"
    out = HBLOCK.sub(anchor, out, count=1)
    if anchor in out:
        out = out.replace(anchor, render_head(page_dir, own_search), 1)
    else:
        m = find_tag(HEAD_END, out)
        if not m:
            return None, "NO </head>"
        out = out[:m.start()] + render_head(page_dir, own_search) + out[m.start():]

    m = find_tag(BODY, out)
    if not m:
        return None, "NO <body>"
    out = out[:m.end()] + "\n" + render(page_dir, page_rel, own_search) + out[m.end():]

    m = find_tag(BODY_END, out, last=True)   # not one in a comment or sample
    if not m:
        return None, "NO </body>"
    out = out[:m.start()] + "\n" + render_foot(page_dir, updated) + out[m.start():]

    note = "chrome"
    if removed:
        note += " (-" + ", -".join(removed) + ")"
    return (out if out != text else None), note


def main(apply_changes):
    changed, problems, removed = 0, [], {}
    todo = list(pages())
    rels = [p.relative_to(ROOT).as_posix() for p in todo]
    dates = content_dates(rels)
    today = datetime.date.today().isoformat()
    n = 0
    for p, pr in zip(todo, rels):
        n += 1
        # A page with no commit yet is being written now.
        new, note = rewrite(p, dates.get(pr) or today)
        if note.startswith("NO "):
            problems.append(f"{pr}: {note}")
            continue
        for what in re.findall(r"-([a-z ]+)", note):
            removed[what] = removed.get(what, 0) + 1
        if note == "excluded":
            removed["chrome, from an excluded page"] = removed.get(
                "chrome, from an excluded page", 0) + (new is not None)
        if new is None:
            continue
        changed += 1
        if apply_changes:
            p.write_text(new)
    print(f"{n} pages, {changed} changed")
    for what, k in sorted(removed.items()):
        if k:
            print(f"   {k} lost the {what}")
    for pr in problems:
        print("   SKIPPED", pr)
    if not apply_changes:
        print("dry run -- pass --apply to write")
    return 1 if problems else 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    sys.exit(main(ap.parse_args().apply))
