#!/usr/bin/env python3
"""Link each exam to its courses, and each course to its exams and the next course.

    python3 tools/build_exam_courses.py            # dry run: print the index
    python3 tools/build_exam_courses.py --apply    # write the blocks

The site is studied course by course for an exam, so a reader needs both
directions: on an exam's page, which courses to study; on a course's page,
which exams it serves. Neither is written by hand. The evidence is the links
the exam pages already carry -- a syllabus map points each line of an official
syllabus at the page that teaches it, so "this map links into Sampling
Theory" is a fact about the map, not a claim about the exam. A course no exam
page links to gets no "Useful for" line rather than a guessed one.

Three generated blocks, each between its own markers:

  exams/<exam>/index.html          "Courses for this exam", in catalogue order
  <course>/index.html (after the banner)   "Useful for: UGC NET, CSIR NET ..."
  <course>/index.html (at the foot)        "Next course in learning order"

The scan leaves out the navigation, the site footer and these blocks
themselves, so the index can never feed on its own output.
"""
import argparse
import importlib.util
import pathlib
import posixpath
import re
import sys
from urllib.parse import unquote

ROOT = pathlib.Path(__file__).resolve().parent.parent

spec = importlib.util.spec_from_file_location("_cat", ROOT / "tools" / "course_catalogue.py")
cat = importlib.util.module_from_spec(spec)
spec.loader.exec_module(cat)
spec = importlib.util.spec_from_file_location("_nav", ROOT / "tools" / "site_nav_model.py")
nav = importlib.util.module_from_spec(spec)
spec.loader.exec_module(nav)

# NET exams first, then the others -- the order the menu uses.
EXAMS = [("ugc-net", "UGC NET"), ("csir-net", "CSIR NET"), ("asrb-net", "ASRB NET"),
         ("iss", "ISS"), ("appsc", "APPSC")]

BLOCKS = {
    "exam": ("<!-- exam-courses: generated by tools/build_exam_courses.py -->",
             "<!-- /exam-courses -->"),
    "useful": ("<!-- useful-for: generated by tools/build_exam_courses.py -->",
               "<!-- /useful-for -->"),
    "next": ("<!-- next-course: generated by tools/build_exam_courses.py -->",
             "<!-- /next-course -->"),
}
# Nothing inside these is evidence: the menu links every course from every
# page, and the generated blocks are this script's own output.
NOT_EVIDENCE = [(r"<!-- site-nav", r"<!-- /site-nav -->"),
                (r"<!-- site-foot", r"<!-- /site-foot -->")] + \
               [(re.escape(a), re.escape(b)) for a, b in BLOCKS.values()]
HREF = re.compile(r'href="([^"#]+)')
IS_STUB = re.compile(r'http-equiv="refresh"')


def strip_not_evidence(text):
    for a, b in NOT_EVIDENCE:
        text = re.sub(a + r".*?" + b, "", text, flags=re.S)
    return text


def course_of(target):
    """('statistics', folder) or ('data-science', slug) for a path inside a course."""
    parts = target.split("/")
    if len(parts) >= 3 and parts[0] in ("statistics", "data-science"):
        return (parts[0], parts[1])
    return None


def build_index():
    """{exam: set of (section, course)} from the links on that exam's pages."""
    known = {("statistics", f) for f, _, _ in cat.statistics_courses()} | \
            {("data-science", s) for s, _ in cat.data_science_courses()}
    index = {}
    for exam, _ in EXAMS:
        d = ROOT / "exams" / exam
        found = set()
        for page in sorted(d.rglob("*.html")):
            text = page.read_text(errors="replace")
            if IS_STUB.search(text[:2048]):
                continue
            here = page.parent.relative_to(ROOT).as_posix()
            for url in HREF.findall(strip_not_evidence(text)):
                if re.match(r"^(mailto:|https?:|//|data:|javascript:|/)", url):
                    continue
                target = posixpath.normpath(posixpath.join(here, unquote(url)))
                c = course_of(target)
                if c in known:
                    found.add(c)
        index[exam] = found
    return index


def labels():
    out = {}
    for _, rows in nav.statistics_rows():
        for lab, href in rows:
            out[("statistics", href.split("/")[1])] = lab
    for _, rows in nav.data_science_rows():
        for lab, href in rows:
            out[("data-science", href.split("/")[1])] = lab
    return out


def ordered():
    """Every course, in learning order: [(key, group, level)]."""
    return ([(("statistics", f), g, lvl) for f, lvl, g in cat.statistics_courses()] +
            [(("data-science", s), g, None) for s, g in cat.data_science_courses()])


def put(text, kind, body, where):
    """Replace this kind's block, or insert it with where(text) -> offset."""
    a, b = BLOCKS[kind]
    block = a + "\n" + body + b if body else ""
    region = re.compile(re.escape(a) + r".*?" + re.escape(b) + r"\n?", re.S)
    if region.search(text):
        return region.sub(lambda m: block + ("\n" if block else ""), text, count=1)
    if not body:
        return text
    at = where(text)
    return text[:at] + block + "\n" + text[at:]


def after_banner(text):
    i = text.index('<div class="banner">')
    h = text.index("</h1>", i)
    return text.index("</div>", h) + len("</div>\n")


def before_own_footer(text):
    """Before the page's own <footer>, or the closing of its main column."""
    foot = text.find("<!-- site-foot")
    body = text[:foot] if foot != -1 else text
    # A page with a <main> column (UGC NET) has its own footer outside it;
    # the block belongs inside the column the reader is following.
    main = body.rfind("</main>")
    if main != -1:
        return main
    own = [m.start() for m in re.finditer(r"\n[ \t]*<footer(?! class=\"sitefoot\")", body)]
    if own:
        return own[-1] + 1
    return body.rfind("</div>")


def exam_block(exam, found, lab, rel_prefix):
    rows = {}
    for key, group, level in ordered():
        if key in found:
            section = "Data Science" if key[0] == "data-science" else group
            tag = ' <small>%s</small>' % level if level else ""
            # The menu labels a Foundation/Advanced pair "(Foundation)"; the tag
            # already says so here.
            name = lab[key][:-len(" (%s)" % level)] if level and lab[key].endswith(" (%s)" % level) else lab[key]
            rows.setdefault(section, []).append(
                '<a href="%s%s/%s/index.html">%s</a>%s' % (rel_prefix, key[0], key[1], name, tag))
    n = len(found)
    if exam == "ugc-net":
        intro = ("UGC NET&rsquo;s ten units are written in full on their own pages, so most of "
                 "what this exam needs is here rather than in a course. These are the courses "
                 "those pages send you to for more.")
    else:
        intro = ("The courses this exam&rsquo;s map sends you to, in learning order &mdash; "
                 "%d of them. Each is listed because the map links into it, not because it was "
                 "judged relevant, so a course missing here is one no line of this syllabus "
                 "points at." % n)
    dl = "\n".join('    <dt>%s</dt>\n    <dd>%s</dd>' % (g, " &middot; ".join(r))
                   for g, r in rows.items())
    return ('<section class="exam-courses" aria-labelledby="courses-for-this-exam">\n'
            '  <h2 id="courses-for-this-exam">Courses for this exam</h2>\n'
            '  <p>%s</p>\n  <dl>\n%s\n  </dl>\n</section>\n' % (intro, dl))


def useful_line(key, index, up):
    exams = [(e, name) for e, name in EXAMS if key in index[e]]
    if not exams:
        return ""
    links = " &middot; ".join('<a href="%sexams/%s/index.html#courses-for-this-exam">%s</a>'
                              % (up, e, name) for e, name in exams)
    return '  <p class="useful-for"><b>Useful for</b> %s</p>\n' % links


def next_line(key, lab, up):
    seq = [k for k, _, _ in ordered() if k[0] == key[0]]
    i = seq.index(key)
    if i + 1 >= len(seq):
        return ""
    nxt = seq[i + 1]
    group = dict((k, g) for k, g, _ in ordered())[nxt]
    return ('  <p class="next-course">Next course in learning order: '
            '<a href="../%s/index.html">%s</a> <small>%s</small></p>\n'
            % (nxt[1], lab[nxt], group))


def main(apply_changes):
    index = build_index()
    lab = labels()
    for e, name in EXAMS:
        print("%-8s %2d courses" % (name, len(index[e])))
    changed = 0

    def write(path, new):
        nonlocal changed
        old = path.read_text()
        if new != old:
            changed += 1
            if apply_changes:
                path.write_text(new)

    for e, _ in EXAMS:
        p = ROOT / "exams" / e / "index.html"
        write(p, put(p.read_text(), "exam", exam_block(e, index[e], lab, "../../"),
                     before_own_footer))
    for key, _, _ in ordered():
        p = ROOT / key[0] / key[1] / "index.html"
        t = p.read_text()
        t = put(t, "useful", useful_line(key, index, "../../"), after_banner)
        t = put(t, "next", next_line(key, lab, "../"), before_own_footer)
        write(p, t)
    print("%d page(s) %s" % (changed, "written" if apply_changes else "would change"))
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    sys.exit(main(ap.parse_args().apply))
