#!/usr/bin/env python3
"""Write the course lists on the Statistics and Data Science hubs from the catalogue.

    python3 tools/build_course_hubs.py            # dry run: say what would change
    python3 tools/build_course_hubs.py --apply    # write

Each hub keeps its own banner, introduction and footer by hand. Between the
markers

    <!-- course-catalogue: generated by tools/build_course_hubs.py -->
    <!-- /course-catalogue -->

this writes the contents list and one card per course, in the topic groups
and the learning order of tools/course_catalogue.py -- the same order the
menu shows, because both read the one list. A card says the course's level
and how many units it has, counted from the folder rather than written down.
"""
import argparse
import importlib.util
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
START = "<!-- course-catalogue: generated by tools/build_course_hubs.py -->"
END = "<!-- /course-catalogue -->"
REGION = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


cat = _load("_cat", ROOT / "tools" / "course_catalogue.py")
nav = _load("_nav", ROOT / "tools" / "site_nav_model.py")


def slug(text):
    t = re.sub(r"&[a-z]+;", " ", text.lower())
    return re.sub(r"[^a-z0-9]+", "-", t).strip("-")


def _is_page(p):
    return p.exists() and 'http-equiv="refresh"' not in p.read_text(errors="replace")[:2048]


def extent(folder, practical_names):
    """'5 units + practical', counted from the folder."""
    units = [p for p in folder.glob("unit*.html")
             if re.fullmatch(r"unit\d+\.html", p.name) and _is_page(p)]
    has_practical = any(_is_page(folder / n) for n in practical_names)
    parts = []
    if units:
        parts.append("%d unit%s" % (len(units), "" if len(units) == 1 else "s"))
    if has_practical:
        parts.append(practical_names[0].split(".")[0])     # "practical" or "lab"
    if not parts:
        return ""
    s = " + ".join(parts)
    return s if units else s.capitalize()


def card(href, level, label, span, blurb):
    tag = " &middot; ".join(x for x in (level, span) if x)
    return ('      <a class="course ready" href="%s">\n'
            '        <span class="status">%s</span>\n'
            '        <h4>%s</h4>\n'
            '        <p>%s</p>\n'
            '      </a>' % (href, tag, label, blurb))


def region(groups, lede):
    """groups: [(group, [card html])]"""
    toc = "\n".join('    <li><a href="#%s">%s</a></li>' % (slug(g), g) for g, _ in groups)
    out = [START,
           '<details class="toc">\n  <summary>On this page</summary>\n  <ol>\n%s\n  </ol>\n</details>' % toc,
           lede]
    for g, cards in groups:
        out.append('  <h2 id="%s">%s</h2>\n  <div class="sem">\n    <div class="courses">\n%s\n    </div>\n  </div>'
                   % (slug(g), g, "\n".join(cards)))
    out.append(END)
    return "\n".join(out)


def statistics_region():
    labels = {h: l for _, rows in nav.statistics_rows() for l, h in rows}
    levels = {f: lvl for f, lvl, _ in cat.statistics_courses()}
    groups = []
    for g, rows in cat.STATISTICS:
        cards = []
        for folder, _ in rows:
            href = f"statistics/{folder}/index.html"
            level = levels[folder] or "Allied"
            cards.append(card(f"{folder}/index.html", level, labels[href],
                              extent(ROOT / "statistics" / folder, ["practical.html"]),
                              cat.BLURB[folder]))
        groups.append((g, cards))
    n = len(cat.statistics_courses())
    lede = ('  <p class="lede"><strong>%d courses, in the order a learner meets them</strong> '
            '&mdash; descriptive statistics before probability, probability before distributions, '
            'distributions before inference. Every course stands on its own, so start with the one '
            'your exam needs. Where a topic has two courses, the <em>Foundation</em> course comes '
            'first and the <em>Advanced</em> course starts where it stops.</p>' % n)
    return region(groups, lede)


def data_science_region():
    labels = {h: l for _, rows in nav.data_science_rows() for l, h in rows}
    groups = []
    for g, slugs in cat.DATA_SCIENCE:
        cards = []
        for s in slugs:
            href = f"data-science/{s}/index.html"
            cards.append(card(f"{s}/index.html", "",
                              labels[href], extent(ROOT / "data-science" / s, ["lab.html"]),
                              cat.BLURB[s]))
        groups.append((g, cards))
    n = len(cat.data_science_courses())
    lede = ('  <p class="lede"><strong>%d courses, grouped by topic and listed in learning order.</strong> '
            'Every course stands on its own &mdash; pick any one and start. All of them are written, '
            'with 358 lab source files behind them: every numeric claim here was produced by running '
            'code.</p>' % n)
    return region(groups, lede)


HUBS = [("statistics/index.html", statistics_region),
        ("data-science/index.html", data_science_region)]


def main(apply_changes):
    bad = cat.problems()
    if bad:
        for b in bad:
            print("catalogue:", b)
        return 1
    changed = 0
    for rel, fn in HUBS:
        p = ROOT / rel
        text = p.read_text()
        if not REGION.search(text):
            print("%s: no course-catalogue markers" % rel)
            return 1
        out = REGION.sub(lambda m: fn(), text, count=1)
        if out != text:
            changed += 1
            if apply_changes:
                p.write_text(out)
    print("%d hub(s) %s" % (changed, "written" if apply_changes else "would change"))
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    sys.exit(main(ap.parse_args().apply))
